### ISSUE TITLE
In examples tb is not defined .

### ISSUE THREAD

**Issue by ats1999** [jscastro76/threebox#105]
```js
render: function(gl, matrix){
						tb.update();
				}
```
I found this code in many examples, but when i run this i got 
```js
ReferenceError
tb is not defined
```

**Comment by jscastro76** [comment]
All the examples are checked with the latest version running on node.js
What’s the example you’re having the issue?

**Comment by jscastro76** [comment]
I have checked again all the examples and all of them work with no issues or errors.
If you can provide a repro, I'll reopen this issue.

**Comment by ats1999** [comment]
> I have checked again all the examples and all of them work with no issues or errors.
> If you can provide a repro, I'll reopen this issue.

It was my folt. I was using this in react.

**Comment by sovanyuthchap** [comment]
@jscastro76, Could fix this issue with react, because I used react, it met this error. please help me!

**Comment by jscastro76** [comment]
> @jscastro76,I installed your framework with npm to my react project and meet this error. Could fix this issue with react? please help me!

Hi @sovanyuthchap, I would need a repro example to help. If you can provide one I could help.

**Comment by sovanyuthchap** [comment]
Hi Jscastro76,

Thank you so much for sent mail to me. Now I fixed this issue. If I have some issues, I’ll contact you later. Your framework is perfect, I stared your repo too.

Best regard

Sovanyuth Chap

**Comment by liujun3660105** [comment]
I have the same error and I have found the reason. In AnimationManager.js，it execute the following code 
```js
  tb.map.repaint = true;
```
and the tb is not defined.so you must define the tb as global variable. const tb = window.tb = new ThreeBox(....)
