### ISSUE TITLE
How can i use this plugin in react-map-gl?

### ISSUE THREAD

**Issue by ats1999** [jscastro76/threebox#106]

**Comment by jscastro76** [comment]
This Three.js plug-in allows you to work directly with mapbox-gl-js, react-map-gl is a wrapper on top of mapbox-gl-js that also allows you some limited 3D capabilities and other 2D/3D visualizations with Deck.gl. 
If your requirement is to use react-map-gl you’ll need to build the wrapper for it as any other js package you want to integrate on it. At the end, this access directly to the mapbox instance so whenever you’re able to instanciate threebox object with the internal mapbox instance as a param, you’ll be able to use it. 
It happens something similar with other products and wrappers of mapbox-gl-js, like in Azure Maps and I was able to use it as it's on top of mapbox-gl-js.
