### ISSUE TITLE
mesh not visible

### ISSUE THREAD

**Issue by skypan** [jscastro76/threebox#116]
react environment, the code is 

`import React, { Component } from "react";
import css from "./styles/index.module.css";
import "mapbox-gl/dist/mapbox-gl.css";

// mapbox-gl is 1.11.1
import mapboxgl from "mapbox-gl";  
import ReactDOM from "react-dom";
// threebox-plugin is 2.1.0
// the url is "https://www.npmjs.com/package/threebox-plugin"
import {Threebox} from "threebox-plugin";

window.tb = null;
export default class Map3d3 extends Component {
  constructor(props) {
    super(props);
    this.map = null;
  }

  render() {
    const { left, top, width, height, id, data } = this.props;

    // 自定义逻辑
    const styles = {
      position: "absolute",
      left,
      top,
      width,
      height,
      textAlign: "center",
    };

    /**
     * 固定格式: 返回的div必须有className/id属性
     */
    return (
      <div className="__easyv-component" style={styles} id={id}>
        
      </div>
    );
  }

  componentDidUpdate() {
    if (this.map) {
      this.map.resize();
    }
  }

  componentDidMount() {
    // let origin = [-122.4340, 37.7353, 1];
    mapboxgl.accessToken =
      "pk.eyJ1IjoianNjYXN0cm8iLCJhIjoiY2s2YzB6Z25kMDVhejNrbXNpcmtjNGtpbiJ9.28ynPf1Y5Q8EyB_moOHylw";
    let origin = [120.51116824150087,
      31.87858714646995, 1];
    let _self = this;
    const dom = ReactDOM.findDOMNode(this);

    this.map = new mapboxgl.Map({
      container: dom.id,
      style: "mapbox://styles/mapbox/light-v9",
      center: origin,
      zoom: 17,
      pitch: 60,
    });

    this.map.on("style.load", function () {
      _self.map.addLayer({
        id: "custom_layer",
        type: "custom",
        renderingMode: "3d",
        onAdd: function (map, mbxContext) {
          tb = new Threebox(
						map, mbxContext,{defaultLights: true}
          );
          
          // three画一个对象
					// instantiate a red sphere and position it at the origin lnglat
					var sphere = tb.sphere({color: 'red', material: 'MeshStandardMaterial'}).setCoords(origin);

          // add sphere to the scene
          tb.add(sphere);
        },

        render: function (gl, matrix) {
          tb.update();
        },
      });
    });
  }
}
`

but the page only show the map without the red mesh, and not erros, i don't why

**Comment by skypan** [comment]
chrome has the message "INVALID_ENUM: bufferData: invalid usage" , may be that's the why but i don't know why

**Comment by skypan** [comment]
i haved solved it, the reason is that my local three's revision is 100, but threebox's three revision is 117, i replace it, and it's ok

**Comment by jscastro76** [comment]
Glad to hear you found the solution by yourself @skypan 
Thanks for using Threebox, let me know if you have any other issue I can help you with
