### ISSUE TITLE
cache functions must be 100% async

### ISSUE THREAD

**Issue by jscastro76** [jscastro76/threebox#117]
```js
this.objectsCache.set(options.obj, {
				promise: new Promise(
					function (resolve, reject) {
						loader(options, cb, function (obj) {
							//console.log("Loading " + options.obj);
							if (obj.duplicate) {
								resolve(obj.duplicate());
							} else {
								reject(obj);
							}
						});
					})
			});
```

**Comment by jscastro76** [comment]
Added async to the two internal functions

**Comment by xzq2325** [comment]
I only load 4 models at the same time, but sometimes the 4 promises are in the pedding state. After waiting for a long time, the downloads is completed at the same time.

**Comment by jscastro76** [comment]
> I only load 4 models at the same time, but sometimes the 4 promises are in the pedding state. After waiting for a long time, the downloads is completed at the same time.

Hi @xzq2325. Without any code or the models you're trying to load is hard to know what's happening and help you with it. 
Some basic questions:
- Are you loading 4 different models or the same model 4 times?
- How big is the model you're trying to load? Can you share it?

**Comment by xzq2325** [comment]
> > I only load 4 models at the same time, but sometimes the 4 promises are in the pedding state. After waiting for a long time, the downloads is completed at the same time.
> 
> Hi @xzq2325. Without any code or the models you're trying to load is hard to know what's happening and help you with it.
> Some basic questions:
> 
> * Are you loading 4 different models or the same model 4 times?
> * How big is the model you're trying to load? Can you share it?
> 
> **EDIT**
> One more question, have you tried to load the same models in a Three.js page without using threebox?

Thanks for your quick reply @jscastro76.
 * 4 different models
 * 400kb、400kb、80kb、15kb。sorry I can not share these models. I had use draco encode these models. And use GLTFLoader with DRACOLoader to load .
 * I tried to load the same models in  https://threejs.org/editor, it looks like ok. use threebox just sometimes load models too long time, but it happens rarely.

**Comment by jscastro76** [comment]
Threebox is not using DRACOLoader, only GLTFLoader, so to have a contrast test you should have a three.js page that load your models with only GLTFLoader. So far, it's not been a priority for me to include DRACOLoader in Threebox as I used to optimize the best format for every model, I can include it in roadmap but I cannot commit on a deadline.

Those sizes are not too big, they should load quickly if the bandwith of the place they are hosted is good (are they hosted locally in your website or remotely downloaded?. I load models from many different sizes including 5 - 10 MB and they load asynchronously. The inconsistent loading timing surprises me, the time shouldn't be very different unless you are debugging or using an important part of your CPU, even removing cache on each call. I have done tests on this a million times, so I'm sure of that.

Having said so, if you are using DRACOLoader is probably because they have compressed meshes and textures, so the real size of the meshes could be up to 10x bigger. I haven't tested any GLB/GLTF models that require compression. I would propose you another contrast test that is to save your models in other format (FBX/DAE/OBJ+MTL) and see the behaviour. It depends on you.

**Comment by xzq2325** [comment]
Thanks for your quick reply @jscastro76.
I modified the GLTFLoader to support draco decode. Maybe I should test in this way.

**Comment by jscastro76** [comment]
Of course you should! Good luck!

**Comment by xzq2325** [comment]
> Of course you should! Good luck!

Thank you!
