### ISSUE TITLE
How to place an image on the map and set altitude to it

### ISSUE THREAD

**Issue by John2397** [jscastro76/threebox#121]
Hello @jscastro76 ,

I would like to place an image on the map.
This can easily be done with mapbox, however, I cannot set an altitude to the image.

For this reason, I thought it might be possible to do it using Threebox, where I could load the image and
treat it as a 3d object. Would such thing be possible, given that Three.js has an `ImageLoader` class?

I also tried to load the image as a texture, and treated it like a 3d object. I managed to display it on the map, but there were a few problems. I can list them if you wish.

**Comment by jscastro76** [comment]
Hi @John2397. Just sharing my thoughts with no code, my first idea would be to create a `PlaneGeometry` with the image as a texture and create a Threebox Object3D with it, similar to what is shown on 01-basic.html. What are the problems you found creating a texture an sticking it in a `PlaneGeometry`?

**Comment by John2397** [comment]
No I didn't use `PlaneGeometry` (Not so much into the world of graphics!). 
Thank you for the guidance.

The only problem now is that I don't know how to match the `PlaneGeometry` size with the image's resolution.
Tried [this](https://stackoverflow.com/a/22365798) but it seems like the size of plane geometry is unit-less, and it ends up being extremely large when I apply the image's width and height as showed on SO answer.

**Comment by jscastro76** [comment]
@John2397 Seeing your new issue, you managed to add your image, right? 
May I close this issue?

**Comment by John2397** [comment]
Yes please.
