### ISSUE TITLE
Add post effect

### ISSUE THREAD

**Issue by likeswinds** [jscastro76/threebox#14]
Allows to add post-effects，Such as [OutlineEffect](https://threejs.org/examples/?q=outline#webgl_postprocessing_outline) ，[UnrealBloomEffect](https://threejs.org/examples/#webgl_postprocessing_unreal_bloom)

**Comment by jscastro76** [comment]
Hi again, @likeswinds . I already have a branch with **BloomEffect**... 
It required to import 9 more modules, which increases a lot the size and also impacts the performance... but it works!! :)
![image](https://user-images.githubusercontent.com/38470852/87219203-8f2fc680-c359-11ea-96d7-8017f4df527e.png)

**Comment by likeswinds** [comment]
https://github.com/mapbox/mapbox-gl-js/issues/8936#issue-516539477
I don't know if it helps

> 再次嗨，@likeswinds。我已经有了**BloomEffect的**一个分支...老实说，我认为它没有什么用，因为它将地图变为黑色...但是为其他着色器和效果打开了大门。
> 它需要再导入9个模块，这增加了很多大小，并且还影响了性能……但是可以！！:)
> ![图片](https://user-images.githubusercontent.com/38470852/87219203-8f2fc680-c359-11ea-96d7-8017f4df527e.png)

https://github.com/mapbox/mapbox-gl-js/issues/8936#issue-516539477
I don't know if it helps

**Comment by jscastro76** [comment]
I´ve been able to apply other postprocessing effects ([I created here a branch](https://github.com/jscastro76/threebox/tree/PostProcessing)) with `AfterimagePass `or `OutlinePass`, including more than one toghether through `EffectComposer`. 
Indeed I finally got Bloom to run transparently, but the problem with Bloom is that the re-render requires to remove the clear call and then when you move the camera or the object is animated it creates a mess because it´s not cleared. So far I don´t find any real scenario where I need to use this.

**Comment by likeswinds** [comment]
Here's an  demo of using Echart ，but  there are other problems with this implementation

https://gallery.echartsjs.com/editor.html?c=xrJHCfsfE- 

Maybe we'll have to find another way， any way , it's done  ,thanks very mach

**Comment by jscastro76** [comment]
Despite the effect is not what we were expecting and the result is not like the sample, closing this issue with the code deployed at [this branch](https://github.com/jscastro76/threebox/tree/PostProcessing)

**Comment by famousgeneral306** [comment]
[this postprocessing branch](https://github.com/jscastro76/threebox/tree/PostProcessing) all example console error : Cannot read properties of undefined (reading 'addPass') --threebox.js:659

**Comment by zhiqunDLUT** [comment]
> [this postprocessing branch](https://github.com/jscastro76/threebox/tree/PostProcessing) all example console error : Cannot read properties of undefined (reading 'addPass') --threebox.js:659

i edit threebox.js , line621, add "this.options = options",  line659 add "this.composer = this.renderer", there well work.
but refresh error, do not clear 3dmodel
![image](https://user-images.githubusercontent.com/31470793/148196643-0155b32d-2841-4d09-bbea-344744a5f4a6.png)
