### ISSUE TITLE
How to keep fixed scale and size of Airplane 3D model when zoom in or out Mapbox?

### ISSUE THREAD

**Issue by sovanyuthchap** [jscastro76/threebox#155]
Hi jscastro76,
I added Airplane 3D model fly with animation on the map, How to keep fixed scale and size of Airplane 3D model when zoom in or out the map ( map.on('zoom',function() {}) )? Help me please.

**Comment by jscastro76** [comment]
Wow... that’s exactly the opposite of what Threebox does, it would require some research... First thoughts you need to get the scale transformation from Threebox camera and invert it only for that object, that would neutralize the transformation being done at tb.world level

**Comment by sovanyuthchap** [comment]
@jscastro76, thank you so much for replying. I'll research and do follow your guide. If I have some issues,  I'll contact you later.

**Comment by jscastro76** [comment]
@sovanyuthchap I think I have very good news for you. I have this feature almost done, I only have to create a property for the object that sets the fixed scale mode

**Comment by sovanyuthchap** [comment]
Dear Jesus,

It's the great news, thank you so much for adding this feature to me. I’ll test it now.

Best regard
Sovanyuth Chap

**Comment by jscastro76** [comment]
> Dear Jesus, It's the great news, thank you so much for adding this feature to me. I’ll test it now. Best regard Sovanyuth Chap

I'm finishing the push to upload it, finishing documentation. I'll comment here when ready to test

**Comment by sovanyuthchap** [comment]
@jscastro76,  Thanks so much brother for your help.

**Comment by jscastro76** [comment]
> @jscastro76, Thanks so much brother for your help.

If you share your animation code, I can add it to the demo example

**Comment by jscastro76** [comment]
![fixedscale2](https://user-images.githubusercontent.com/38470852/105159700-a8d37700-5b0f-11eb-9f1f-70ca2c74e7c2.gif)  
It was by far harder than what I stimated initially, because it impacts deeply the way the objects are being positioned and animated, apart from the shadows, bounding box... Here it is finally... 
You can find [the new example on how to create objects with fixed scale here](https://github.com/jscastro76/threebox/blob/master/examples/19-fixedzoom.html) 

Enjoy!

**Comment by sovanyuthchap** [comment]
Wow, I just see, thank you so much brother that helping resolve my task. Sorry that I reply you late, because I busy work on another project. The project that use your framework, my company pause it, waiting util company customer tell continue. And I can't share code with you, because it's my company policy. When my boss give me continue, I'll see and merge your code to my project.

**Comment by jscastro76** [comment]
No problem @sovanyuthchap, I totally understand. 
I hope this feature covers your needs, I added explicitly an airplane demo because of your request, the path is at the end not very relevant.
