### ISSUE TITLE
MERCATOR_A constant unused

### ISSUE THREAD

**Issue by lights0123** [jscastro76/threebox#158]
in src/utils/constants.js, `MERCATOR_A` is defined as a file-local constant:

https://github.com/jscastro76/threebox/blob/36d9de720b37ff1acbc23620c1e54b1c2a5f49d2/src/utils/constants.js#L2

However, when exported, the very similar—but not quite the same—`EARTH_RADIUS` constant is used instead:

https://github.com/jscastro76/threebox/blob/36d9de720b37ff1acbc23620c1e54b1c2a5f49d2/src/utils/constants.js#L10

That makes the earlier defined `MERCATOR_A` constant unused. Is this a copy/paste error, or is this truly the way it should be?

**Comment by jscastro76** [comment]
Hi @lights0123 
That's a great question, the fact is that the most precise value is ` const MERCATOR_A = 6378137.0; // 900913 projection property ` but is not the one used by Mapbox which includes [hardcoded](https://github.com/mapbox/mapbox-gl-js/blob/0063cbd10a97218fb6a0f64c99bf18609b918f4c/src/geo/lng_lat.js#L11)  the following:
```js
/*
* Approximate radius of the earth in meters.
* Uses the WGS-84 approximation. The radius at the equator is ~6378137 and at the poles is ~6356752. https://en.wikipedia.org/wiki/World_Geodetic_System#WGS84
* 6371008.8 is one published "average radius" see https://en.wikipedia.org/wiki/Earth_radius#Mean_radius, or ftp://athena.fsv.cvut.cz/ZFG/grs80-Moritz.pdf p.4
*/
export const earthRadius = 6371008.8;
```
So, to be accurate with Mapbox calculations I decided to modify it to the value they use.

Are you finding any issue in your calculations?

**Comment by lights0123** [comment]
Nope. However, I'm wondering if the unused constant should be removed and a comment added explaining the use of `EARTH_RADIUS`.

**Comment by jscastro76** [comment]
@lights0123 updated the comment, but I decided not to remove the local variable
