### ISSUE TITLE
How can I get coordinates when the model follow path with line?

### ISSUE THREAD

**Issue by codingBingo0309** [jscastro76/threebox#163]
The model  play animation & follow path, it works very well.
But I can't get coordinates by the function followPath callback, so what can I do for this sence?
Thanks very much!

**Comment by jscastro76** [comment]
Are you looking to get the coords on every segment line or you need the coords in every frame?

**Comment by codingBingo0309** [comment]
> Are you looking to get the coords on every segment line or you need the coords in every frame?

I need the coords in every frame, because of I need focus on the model in every frame.
When the model moved, I can move the map to focus on the model.

**Comment by jscastro76** [comment]
I was thinking while ago on adding a new event #41. For what you need it would be needed. I’ll take a look to it as a new feature

**Comment by codingBingo0309** [comment]
Oh, it's my pleasure！

**Comment by codingBingo0309** [comment]
Oh, it's my pleasure! I'm waiting for your new feature.

**Comment by jscastro76** [comment]
@codingBingo0309 godd news, this event is already included at the Object3D level and it's [documented here](https://github.com/jscastro76/threebox/blob/master/docs/Threebox.md#objectchanged). You can check it's behavior in [this example](https://github.com/jscastro76/threebox/blob/master/examples/05-logistics.html)
