### ISSUE TITLE
Feature Request. Can we bring postprocessing 3d lut to threebox

### ISSUE THREAD

**Issue by pundirmr** [jscastro76/threebox#164]
Can we bring postprocessing 3d lut to threebox
example:
https://threejs.org/examples/?q=post#webgl_postprocessing_3dlut

**Comment by jscastro76** [comment]
Hi @pundirmr 
I created a [branch while ago on some post processing effects](https://github.com/jscastro76/threebox/tree/PostProcessing). You can find the thread in this issue #14. You can fork it to check it out and try with the effect you are looking for following the same pattern.
Long story short, I decided to not include it in the continuous release for several reasons:
- It affects seriously the performance, despite it depends on the effect, most of them require two or more passes in the `EffectComposer` which reduces seriously the FPS rate.
- It makes Threebox very heavy. That’s why also Three.js excluded post processing from the core.
- Some effects conflict with Mapbox and the renderer clear order, such as Bloom.
- Once applied affects all the scene. I was very interested in some post processing effects but I wanted to apply only to specific objects on events such as mouseover or selected.  
For all of this I’m not considering to include post processing in Threebox
