### ISSUE TITLE
Tooltips on 3d models

### ISSUE THREAD

**Issue by tiagoFonseca1109** [jscastro76/threebox#165]
Hello,

I´ve been trying to enable tooltips on some imported 3D models, but it isnt working.

I already enabled tooltips in threbox, and I enabled tooltips in the options for the 3d element, as shown below. 
```
tb = new Threebox(
	map,
        mbxContext,
	{
		realSunlight: true,
		enableSelectingFeatures: true, //change this to false to disable fill-extrusion features selection
		enableTooltips: true // change this to false to disable default tooltips on fill-extrusion and 3D models 
	}
);
```

```
var proptions = {
	obj: './models/er.glb',
	type: 'gltf',
	scale: 10,
	units: 'meters',
	rotation: { x: 90, y: 0, z: 0 }, //default rotation
	anchor: 'center',
	adjustment: { x: 0, y: 0, z: 0.4 },
	enableToltips: true
}
```
When i load the object i did the following:
```
tb.loadObj(proptions, function (model) {
	model.setCoords(place);
	model.addTooltip("A radar in the middle of nowhere", true);
	model.setRotation({ x: 0, y: 0, z: Math.floor(Math.random() * 100) })
	tb.add(model);
});
```

Although the object appears in the render, when I put the mouse above or i click it nothing shows the tooltip.

What am I missing ?

**Comment by jscastro76** [comment]
Can you post the full code of your page? There are 18 examples, most of them using tooltips, including [the one you have used for these lines](https://github.com/jscastro76/threebox/blob/master/examples/12-add3dmodel.html) with the radar model.
You have weird things here... 
- `enableToltips: true` in `var proptions`  doesn't exist in `loadObject` options, I would remove it.   
- You create the tooltip `model.addTooltip("A radar in the middle of nowhere", true);` where the second param to true means using mapbox style, so check if you're adding the link to the style sheet `<link href="./css/threebox.css" rel="stylesheet" />` the tooltip won't be rendered properly

**Comment by jscastro76** [comment]
I downloaded the page you shared in the chat, and I found many different issues and mistakes in your code.

 **1.** You're using the wrong property to enable the selection of 3D objects, you use `enableSelectingFeatures: true, //change this to false to disable fill-extrusion features selection`, that is for Mapbox fill-extrusions features as said in the comment, but not for 3D models and objects, you have to use `enableSelectingObjects: true`. Only adding this, your problem with the tooltips on mouse over will be solved.

```js
tb = new Threebox(
    map,
        mbxContext,
    {
        realSunlight: true,
        enableSelectingObjects: true, //enable 3D models over/selection
        enableTooltips: true // enable default tooltips on fill-extrusion and 3D models 
    }
);
```

But I have found other issues...   
**2.** Your models `scale` initialization is too small, so you are hiding them below the big shapes you have created. The scale of your bus stop is `scale: 0.01` and you define a place which is on the ground `var place = [element.lng, element.lat, 0];`, so it's hidden inside this `CylinderGeometry`
[![enter image description here][1]][1]
If you use `scale: 1` you will see how your bus stops raises from the cylinder.
[![enter image description here][2]][2]

**3.** Same with the bus, you initialize them with `scale: 1,` which make them be hidden below the tubes and cylinders you have created. If you initialize them with `scale: 10,` and you elevate them 5 meters from the floor `let truck = model.setCoords([lngB, latB, 4]);` then you will see them raising.
[![enter image description here][3]][3]

**4.** Your models have a wrong initialization params mixing `anchor` and `adjustment`. `anchor: center` will center the pivotal center of your object properly, but then you apply negative values to x and y (which means decenter the object), and a z value that elevates the pivotal center `adjustment: { x: -0.1, y: -0.1, z: 0.4 }`. If you want your model on altitude use the 3rd coord in `setCoords`.

**5.** Your Cylinders and Tubes for the bus stops and bus lines are huge, and also they have the wrong init params, as you set them below the ground level `-0.4` units `adjustment: { x: 0, y: 0, z: -0.4 }` (something supported by Mapbox but very bad resolved and producing weird effects. My recommendation would be to make them almost flat and at the ground level with no `adjustment` param. `const geometry = new THREE.CylinderGeometry(0.6, 0.6, 0.01, 32);`. 

Summarizing, check all of these changes and let me know if it works.

  [1]: https://i.stack.imgur.com/legKR.png
  [2]: https://i.stack.imgur.com/9PKdR.png
  [3]: https://i.stack.imgur.com/95O9n.png
  [4]: https://github.com/jscastro76/threebox/blob/master/examples/README.md
  [5]: https://i.stack.imgur.com/PVXn2.png
  [6]: https://github.com/mapbox/mapbox-gl-js/issues/9814
  [7]: https://jsfiddle.net/p83uog9w/7/
  [8]: https://i.stack.imgur.com/6J7vI.png
  [9]: https://i.stack.imgur.com/k3qJa.png
  [10]: https://i.stack.imgur.com/DfGsd.png
  [11]: https://i.stack.imgur.com/W6E91.png
  [12]: https://threejs.org/editor/
