### ISSUE TITLE
Question about Tooltip on Line

### ISSUE THREAD

**Issue by fnb17** [jscastro76/threebox#166]
Hello,
Is it possible to add a tooltip to a Line? If yes then how could I do it? I know how to add to Object3D using the addTooltip, but with lines I can't figure it out.
Thanks in advance!

**Comment by jscastro76** [comment]
Hi @fnb17 
A tooltip is only for Object3D that can be overed/selected. 
The option you have for not selectable objects is to use a label through [`tb.label`](https://github.com/jscastro76/threebox/blob/master/docs/Threebox.md#label) which is an object 3D by itself, so then you can position it as a pure 3D object. Something like this:

```js
let label = tb.label({ htmlElement: html, alwaysVisible: true, feature: feature })
	.setCoords(location);
tb.add(label, layerId, sourceId);
```

**Comment by jscastro76** [comment]
Discussed and resolved in stackoverflow https://stackoverflow.com/questions/65644945/threebox-tooltip-in-3d-models

**Comment by fnb17** [comment]
My problem is that I wanted to be able to raycast like in this example : https://threejs.org/examples/webgl_interactive_lines.html, showing the tooltip when intersected a line.  I tried to use THREE.MeshLine to create a mesh, made mesh.raycast = MeshLineRaycast, then send it to tb.Object3D, I set the anchor to center and  .setCoords to the middle point of line,  and it now works. By the way, when It intersects and shows tooltip, a rectangle also appears around the object, is there a way I can hide it?

**Comment by jscastro76** [comment]
You can use `bbox: false` in the initialization of the Object3D for your `THREE.Meshline`. That should keep the raycast but hide the bounding box

**Comment by jscastro76** [comment]
@fnb17 You made me realize about a bug... `bbox: false` does not work as expected!! Can you share a bit of the code of the lines you are adding... I want to repro it and be sure `bbox: false` works as expected
Re-tagging this to bug 🐞

**Comment by fnb17** [comment]
Here is a bit of code that I use:

 var resolution = new THREE.Vector2( window.innerWidth, window.innerHeight );
 let mat = new MeshLineMaterial({
              color: line.color,
              opacity: 1,
              resolution: resolution,
              sizeAttenuation: 1,
              lineWidth: 2,
              depthTest: false,
              transparent: false            
            });

var straightProject = utils.lnglatsToWorld(lineSegment.geometry);
	            var normalized = utils.normalizeVertices(straightProject);
              var flattenedArray = utils.flattenVectors(normalized.vertices);
              let line2 = new MeshLine();
              line2.setPoints(flattenedArray);
              let middlepoint={
                x: (lineSegment.geometry[0][0]+lineSegment.geometry[1][0])/2,
                y: (lineSegment.geometry[0][1]+lineSegment.geometry[1][1])/2
              }
              let mesh = new THREE.Mesh(line2.geometry, mat);
              mesh.raycast = MeshLineRaycast;
               let lineX = tb.Object3D({obj: mesh,anchor:"center", bbox:"false"});
              lineX.setCoords([middlepoint.x,middlepoint.y, 0]);
              lineX.addTooltip("Linha :", true);
 	      tb.add(lineX); 


lineSegment.geometry is like [ [lon1,lat1] , [lon2,lat2] ]

I've used the threebox utils to calculate the flattened array.
Btw the raycast with this is just little bit innacurate, but it gets the job done

**Comment by jscastro76** [comment]
Thanks for the code, I'll check that out asap and I'll review also the raycast accuracy.

**Comment by jscastro76** [comment]
Now `bbox: false` should not show the bounding box even if an object is raycasted. Please check if that solves your issue

**Comment by fnb17** [comment]
That solved the issue, thank you very much!
