### ISSUE TITLE
Update to Three.js 127

### ISSUE THREAD

**Issue by jscastro76** [jscastro76/threebox#169]
Some issues already detected:

- [x] Despite some demos work as is, without any change, demos with only one object the object (i.e. 01-basic.html) is loaded but suddenly disappear. It requires investigation because with 2 objects it doesn't happen.
- [x] evented.js:140 Error: THREE.Geometry is not a constructor [buffergeometry](https://stackoverflow.com/questions/66874065/three-js-r125-buffergeometry-vertices-does-not-exist)
- [X] The bug (#16) on the duplicate has been solved.
- [X] Shadows have dissapear, even in the simplest example (add3dmodel). In the meantime, I open a comment in the PR  
- [X] Creating a different context instead of reusing Mapbox. [solved by Three.js team](https://github.com/mrdoob/three.js/pull/21281)
- [ ] Review the loaders, it's probably they are misaligned with the current version.
- [ ] FBXLoader now depends on fflate. Other decompression libs (JSZip and ZLib) are not used anymore.
- [ ] Issues with the buffer in console. `[.WebGL-0000022C33E91040] GL_INVALID_OPERATION: Insufficient buffer size.`
- [ ] In logistics.html demo. Uncaught TypeError: Cannot set property target of #<Event> which has only a getter

**Comment by fsteggink** [comment]
You might want to upgrade to Three.js@0.126.1. Please see this advisory: https://www.npmjs.com/advisories/1639.

**Comment by jscastro76** [comment]
> You might want to upgrade to Three.js@0.126.1. Please see this advisory: https://www.npmjs.com/advisories/1639.

Thanks for the warning, @fsteggink ! So far, there are other issues to find a workaround
