### ISSUE TITLE
Collisions between objects

### ISSUE THREAD

**Issue by SlimBot27** [jscastro76/threebox#171]
I'm using ThreeBox to build and design a map with 3D Objects. Is there any way for me to check within ThreeBox if two or more objects are colliding?

**Comment by jscastro76** [comment]
That feature is not yet implemented nor in the immediate roadmap.

**Comment by jscastro76** [comment]
Have you coded anything on this topic?

**Comment by SlimBot27** [comment]
I compared the positions. If it collided with a certain point (2D) I
stopped it from moving.

Jesus Serrano <notifications@github.com> escreveu no dia sexta, 22/01/2021
à(s) 06:26:

**Comment by jscastro76** [comment]
That’s ok for objects in the same plane but it wouldn’t work for objects with different altitude. But if it works for your scenario, great!!
Anyway, implementing a built-in collisions detection is in the backlog but there are many caveats like objects animated and scaled by a container group... I will go for it as soon as possible

**Comment by SlimBot27** [comment]
Oh, that's fine, no need to worry. My group was using the technology for
university work but we have already finished it. Thank you anyway, it was
really helpful.

Jesus Serrano <notifications@github.com> escreveu no dia sábado, 23/01/2021
à(s) 09:32:

**Comment by jscastro76** [comment]
Yeah I saw a lot of them at StackOverflow asking for similar things and WASD interactions, camera movements...
