### ISSUE TITLE
Vue.js example

### ISSUE THREAD

**Issue by ahoedholt** [jscastro76/threebox#172]
Does anyone have a simple example of Threebox used in a Vue.js project?

Thank you!

**Comment by jscastro76** [comment]
I think @luojiandan was working on Vue.js

**Comment by jscastro76** [comment]
@ahoedholt is there any repo you are working with vue.js and you found any issue?

**Comment by ahoedholt** [comment]
@jscastro76 I don't have a public repo for the project at the moment, I'm first of all just trying to make one of the simple examples work. I just found the following, but I haven't been able to transfer it to my project yet (and it may also be based on the older Threebox library):
https://github.com/peterpolman/hidden-layers/blob/develop/src/components/BaseMap.ts

I'll work on it some more and post an example if successful. If anyone has other Vue.js+Threebox implementations, feel free to share :)

**Comment by jscastro76** [comment]
Let me know once you have an issue, I haven’t worked yet in vue.js but if you setup any working example I could help you if you have any issue

**Comment by ahoedholt** [comment]
Thank you, @jscastro76! I will post a setup once I'm a bit further. But first of all, when installing the library through npm, would there be any issue importing it with npm import, e.g. `import Threebox from 'threebox-plugin';` ? I'm asking since I keep getting the error `Error: threebox_plugin__WEBPACK_IMPORTED_MODULE_0___default.a is not a constructor
    at mapbox-gl.js:31`, so I just want to make sure that it's imported correctly before proceeding.

**Comment by KarimJedda** [comment]
This is how I use in Svelte:

import threebox from 'threebox-plugin/dist/threebox';

in case that helps. With your updated version (import {Threebox} ...) I was getting issues when building the project.

**Comment by luojiandan** [comment]
> Does anyone have a simple example of Threebox used in a Vue.js project?
> 
> Thank you!

@ahoedholt I use threebox+mapbox gl in Vue.js.
can you send me your code?I try.
@jscastro76 let me try.

**Comment by jscastro76** [comment]
Hi @ahoedholt, I managed to create a [super simple codesandbox with vue.js](https://codesandbox.io/s/cool-feistel-jqyw5?file=/index.html). 
It's not definitely a component-based, but I'm sure you can extrapolate.

**Comment by ahoedholt** [comment]
Thank you, @jscastro76! I actually had time to work on it yesterday evening as well and got it working - sorry for the delayed reply. My example is almost identical to yours, so I won't post it here. However, I can confirm that @KarimJedda's suggestion for import, `import threebox from 'threebox-plugin/dist/threebox';` works very well. I played around with multiple aspects of the library, including importing objects as well as using custom Three.js Object3D. With Object3D I integrated a custom animation in the map, and I can confirm that everything works flawlessly. One tip is that if you want to divide the creation of e.g. objects into separate Vue methods, you can't call them directly from within onAdd or render without first exposing `this` outside the scope, e.g. by declaring the variable `let _this = this;`

A bit off-topic, but the only issue I'm currently having is actually Mapbox's limitation in triggerRepaint(), where all layers (including the map) is forced to repaint even with the tiniest Object3D animation. This is obviously ressource-hungry; I know that Mapbox is working on a solution to this, but in the meantime I'm trying to see if I can integrate the Threebox layers into another WebGL context that is synced with the Mapbox layer (sort of like how Deck.gl does it).

**Comment by ahoedholt** [comment]
Also, I forgot to mention that I'm running it with Mapbox 2.0 and I haven't encountered any issues yet. I remember seeing in a previous thread that Mapbox 2.0 wasn't supported yet, but at least it doesn't cause any major problems.

**Comment by jscastro76** [comment]
That's great to hear, I'd love to see that demo code to improve the code sandbox with the practices you're describing. 
using default option `{ passiveRendering: true }` should reduce a lot the number of times `triggerRepaint()` is being called. 

Anyway, I was thinking on using separated contexts because of the issues I`ve found with three 1.24 #169. Indeed, unless we do it in that way, we won't be able to update to latest versions of three as I discussed with the project owners in [StackOverflow](https://stackoverflow.com/questions/65707255/change-from-three-js-v122-to-v123-hides-the-shadows-on-a-custom-layer-for-mapbox) and their own [repo](https://github.com/mrdoob/three.js/pull/20732) 

I have several things to review and investigate before considering threebox is updated to Mapbox 2.0. One of them is the depth calculation for pitch > 60
![6](https://user-images.githubusercontent.com/7702529/103185815-ff76d800-48f8-11eb-8a7c-72ba3df45f7f.gif)

**Comment by ahoedholt** [comment]
@jscastro76 I'll extract the example out of my codebase and post it here asap (the entire project is a bit complex with a mix between Deck.gl, raw WebGl and Threebox, which is why I didn't post it yet). In terms of the `triggerRepaint()` I don't have any performance issues with default objects, Threebox animations etc., but when integrating a custom Object3D (where the animation methods are defined within the Three.js objects) I have to explicitly call `map.triggerRepaint()` every time I call the animation method in the Three.js object for the animations to run - otherwise they'd stop until I pan the map. I might be able to optimize it in other ways and perhaps use the Threebox animation features, but I figured it could be fun to try with a separate context as well to keep the repaints completely separate from the map.

**Comment by jscastro76** [comment]
@ahoedholt Whatever you can improve in the vue.js sample code will be greatly appreciated. If you do it, I will add it to the samples and the documentation, thanks in advance for your contribution, it will help others with the same issue you had.

Regarding the performance and using a second context, when I did my first research on the topic, I found a quite old issue in Mapbox where a guy tested all the different options, including having a fully separated context and even 2 mapbox instances, one of them empty. [Here is the link](https://github.com/baptistemanson/mapbox-custom-layers)

The performance was obviously better in terms of performance/memory, but there were other collaterals that I would personally wouldn't assume for threebox, like losing the depth calculation between mapbox fill-extrusions and 3D custom layer. 

|Sharing context|Different contexts
|-----------------|--------------------
|![image](https://user-images.githubusercontent.com/38470852/105459255-389d3080-5c8a-11eb-881c-168b228d698c.png)|![image](https://user-images.githubusercontent.com/38470852/105459291-4a7ed380-5c8a-11eb-866e-2cf1fe3c267f.png)

The second issue is the latency between the movement of both cameras. While current sharing context ensures the objects are fixed and stuck to a coords set, creating different contexts will produce a soft dragging effect where the latency between the 2 contexts render can be visually perceived when the map moves first and the 3D objects follow. It's perceivable even with ne single cube, so with thousands of objects will be definitely clearer.  
![3contexts](https://user-images.githubusercontent.com/38470852/105459835-325b8400-5c8b-11eb-9661-1dd2f3b6c8a9.gif)

There's one more test that I would do, is just to create a new context but paint in the same canvas the map is... theoretically speaking, that would solve these two issues keeping at the same time a good performance... but that's a test I haven't done yet.

**Comment by ahoedholt** [comment]
@jscastro76 Thank you, I will look into the link you provided for the custom context! It's definitely an issue with the dragging effect - and of course it would be easier if there could be both a custom Mapbox layer in the same context and good performance. I do know that Mapbox is working on rendering of only the custom layer (see e.g. https://github.com/mapbox/mapbox-gl-js/issues/8159). But I'm aware that you would probably still have the issue with the latest Three.js version that you mentioned earlier.

I made some simple examples with Vue.js and Threebox - currently some spheres and a custom Pulse object based on [this](https://github.com/jscastro76/threebox/issues/49).
Here's the CodeSandbox: [Vue Threebox Examples](https://codesandbox.io/s/zen-dream-l28zc?file=/src/components/ThreeboxExample.vue)

As you can probably tell, the pulse part is very ressource-demanding since I have to call triggerRepaint manually on each render loop (I still haven't found a way to optimize this, suggestions are welcomed!).

Please let me know if you'd like me to create a specific example in Vue.js that could be a part of the documentation.

**Comment by jscastro76** [comment]
https://stackoverflow.com/questions/50824353/mapbox-style-changes-breaks-on-zoom-when-a-layer-is-added

**Comment by jscastro76** [comment]
@ahoedholt I have added your example to the doc. I cloned your sandbox to do some adjustments, but your base still intact. You're also added to the [examples doc with your alias](https://github.com/jscastro76/threebox/blob/master/examples/README.md#vuejs-sample) in attribution to your work and contribution. Thanks again
