### ISSUE TITLE
dK is undeclared

### ISSUE THREAD

**Issue by KarimJedda** [jscastro76/threebox#173]
Hi there, it's me again :) 

When integrating the package into an npm project everything works fine during the development (npm run dev)

Things get a bit hairy when running 'npm run build', in this case a ReferenceError is thrown for this line

https://github.com/jscastro76/threebox/blob/12a6f6a5c2fd4fe4fcc91822a3c68f9c7dd4ef68/src/Threebox.js#L476

Where dK is not referenced, I believe that should be a comma between the 83 and dK right? 

If that's the case let me know I'll make a PR.

**Comment by KarimJedda** [comment]
Same with v3 (L19279) and objectState (L1450)

**Comment by KarimJedda** [comment]
I went ahead and did it: 
https://github.com/jscastro76/threebox/pull/174

**Comment by jscastro76** [comment]
[Merged 174](https://github.com/jscastro76/threebox/pull/174 )! Thanks for taking the time to cleaning it up
