### ISSUE TITLE
Passing in tb manually instead of relying on window.tb

### ISSUE THREAD

**Issue by mayteio** [jscastro76/threebox#178]
Hey, I'm using React with threebox and due to code structure, I have to instantiate `window.tb` elsewhere than right before I access it to add meshes to the map.

Is there a way I can pass my own instance of `Threebox` instead of the plugin relying on the fact that `window.tb` will always be there? It's causing some race cases and doesn't feel like the best way to do things.

Cheers,
Harley

**Comment by jscastro76** [comment]
The only thing you need to instantiate Threebox is the Mapbox instance already created. You can instantiate Threebox just immediately after the Mapbox instance or defer it to the different Mapbox events (i.e `map.on('style.load’, ...`). Also you can instantiate it in your first layer `onAdd` method.

Without seeing your code or a pseudo-code example is hard to know what you’re trying to do and the issue you are facing. Do you have any repo I can look at?

**Comment by jscastro76** [comment]
Hi @mayteio 
Do you have any minimal reproducible example on your issue?

**Comment by mayteio** [comment]
Hey, sorry @jscastro76 I was pulled onto something else. My issue was getting this working in a provider friendly way for a React app.

For anyone else in the future, I'm using [`react-map-gl`](), and was able to provide `tb` to my app using the following provider:

1. Wrap your app in `MapContext.Provider` from 'react-map-gl'
2. Wrap your app as a child of the MapContext.Provider with the following provider:
```typescript
import React, { createContext, useContext, useEffect, useMemo } from 'react';
// @ts-ignore
import { Threebox } from 'threebox-plugin';
import { MapContext } from 'react-map-gl';

/** Type return values */
// interface ThreeboxContextValue {}

/** Generate the context */
const ThreeboxContext = createContext<any | undefined>(null);

/** Provider to wrap your app with */
export const ThreeboxProvider: React.FC = ({ children }) => {
  const { map: mapbox } = useContext(MapContext);
  const tb = useMemo(() => {
    if (mapbox) {
      return new Threebox(mapbox, mapbox.getCanvas().getContext('webgl'), {
        defaultLights: true,
      });
    }
  }, [mapbox]);

  /** Set it globally so the script can find it */
  useEffect(() => {
    if (tb) {
      (window as any).tb = tb;
    }
  }, [tb, mapbox]);

  return <ThreeboxContext.Provider value={tb}>{children}</ThreeboxContext.Provider>;
};

/** Hook to consume the context */
export const useThreebox = () => {
  const context = useContext(ThreeboxContext);
  return context;
};
```

You can then use tb in hooks like so:
```typescript
import { useEffect, useState, useContext } from 'react';
import { useThreebox } from './ThreeboxProvider';
// important!
import { THREE } from 'threebox-plugin';
import { MapContext } from 'react-map-gl';

const geometry = new THREE.CylinderGeometry(0.2, 0.2, 5, 20);
const material = new THREE.MeshToonMaterial({ color: 0xe50e56 });
const mesh = new THREE.Mesh(geometry, material);
geometry.rotateX(Math.PI / 2);

export const useThreeboxLayer = () => {
  const threebox = useThreebox();
  const {map:mapbox} = useContext(MapContext);

  const [layer, setLayer] = useState<any>();
  useEffect(() => {
    if (threebox) {
          setLayer({
            id: 'my-threebox-layer',
            type: 'custom' as any,
            renderingMode: '3d',
            onAdd: function () {
              const obj = threebox
                .Object3D({ obj: mesh, anchor: 'center' })
                .setCoords([0, 0, 1]);

              threebox.add(obj);
            },
            render: function () {
              if (threebox) {
                threebox.update();
              }
            },
          })
    }
  }, [threebox]);

  useEffect(() => {
    if (mapbox && layer && threebox) {
      threebox.clear(); // play nice with new react hot loader
      mapbox.removeLayer('my-custom-layer'); // play nice with new react hot loader
      mapbox.addLayer(layer);
    }
  }, [layer, mapbox, threebox]);
};
```

**Comment by mayteio** [comment]
The issue was that internally, threebox relies on `window.tb` being available at window.tb - there's no way to inject it. So to make it available, you have to first assign it to window.tb in your provider, and only return tb to the hook value after that's done.

**Comment by jscastro76** [comment]
Glad to hear you were able to solve it by yourself. If you want to provide a code example I will include it in the examples, that will help other users with the same issue
