### ISSUE TITLE
How to change the camera position in threebox?

### ISSUE THREAD

**Issue by SergioCarreirinha** [jscastro76/threebox#185]
I'm using ThreeBox to build and design a map with 3D Objects. Is there any way to change the camera position in ThreeBox?

I am supposed to put the camera behind an object and make it navigate in the third person, but my first problem is how to position the camera behind the object.

**Comment by jscastro76** [comment]
To change the camera you only have to change the map camera through `map.flyTo` where you can specify coords, zoom, pitch y bearing to find your desired position. Indeed I personally use this feature in all my projects adding these attributes to the `feature.properties` That I use to generate every 3D object

**Comment by SergioCarreirinha** [comment]
Do you think that it is the most advisable to do the third person navigation through the map?

**Comment by jscastro76** [comment]
> Do you think that it is the most advisable to do in the third person navigation?
> I need to move an object with the WASD keys around the map and with the camera follow that same object

I don’t know what you’re doing, it all depends on what you’re trying to achieve and what’s the objective of you map. What you describe seem like a GPS Navigation-like view, so those use to move as a first  person  always, keeping the arrow that represents the car in the bottom center position and rotating the map around. If you use a top vertical view you can also use `map.panTo`.

But did the answer solved your question?

**Comment by SergioCarreirinha** [comment]
The main goal is to do a third person navigation like this one: https://codepen.io/Fyrestar/pen/oNxERMr but above of the mapbox map.

**Comment by jscastro76** [comment]
> The main goal is to do a third person navigation like this one: https://codepen.io/Fyrestar/pen/oNxERMr but above of the mapbox map.

Then yes my, you should use third person view with `map.flyTo`, `map.jumpTo` or `map.panBy`, depending on the code and smooth transition you are looking for

**Comment by SergioCarreirinha** [comment]
So for that I will have to render the map and the object position when I press any key, right?

**Comment by jscastro76** [comment]
> So for that I will have to render the map and the object position when I press any key, right?

@SergioCarreirinha what have you coded so far? The issues are not for infinite Q&A but for bugs, resolving problems and features.
You should work first on a minimal reproducible example on fiddle, codepen or codesandbox then we can discuss over something concrete on the points you are stuck. You have many examples here that you can reuse, specially logistics, raycaster and fixedZoom samples and in Mapbox you have also one on [moving through the map with game-like controls](https://docs.mapbox.com/mapbox-gl-js/example/game-controls/)
Please, do your side, I can help if you are blocked on any code issue

**Comment by jscastro76** [comment]
Question resolved
