### ISSUE TITLE
renderer antialias is not work

### ISSUE THREAD

**Issue by skypan** [jscastro76/threebox#205]
**Threebox version**:
2.2.0
### Question
i use the geojson to draw building, but the buildings's effect is not good, the effect of antialia is serious
webglrenderer options is below :
this.renderer = new THREE.WebGLRenderer({
			alpha: true,
			antialias: true,
			preserveDrawingBuffer: options.preserveDrawingBuffer,
			canvas: map.getCanvas(),
			context: glContext
		});
can you help me for it , thank you very much 
![截图录屏_选择区域_20210223170926](https://user-images.githubusercontent.com/11325807/108824011-2a7d5f80-75fc-11eb-8619-6b60e1015527.png)
![截图录屏_选择区域_20210223172415](https://user-images.githubusercontent.com/11325807/108824037-32d59a80-75fc-11eb-8b8d-839f64000b61.png)

**Comment by skypan** [comment]
this is my building.json and texture
![material](https://user-images.githubusercontent.com/11325807/108824857-33226580-75fd-11eb-977d-7d587e041ef2.png)

[build1.zip](https://github.com/jscastro76/threebox/files/6027943/build1.zip)

**Comment by jscastro76** [comment]
What method are you using to create the buildings?

**Comment by skypan** [comment]
i found the example of 01-basic.html is not good
![截图录屏_选择区域_20210223181021](https://user-images.githubusercontent.com/11325807/108828922-729f8080-7602-11eb-87ac-a01220e10c09.png)

**Comment by skypan** [comment]
only use threejs to draw box is good, but in threebox , the effect is not good,the theejs version is same
![截图录屏_选择区域_20210223204353](https://user-images.githubusercontent.com/11325807/108845019-dc765500-7617-11eb-8a0a-884d1fbf2f5c.png)

**Comment by jscastro76** [comment]
Not sure what's the issue you're facing because you don't add code, browser version, you're comparing with Three v.106 when in Threebox is used v.117. As you can see the render of 01-basic looks like this in my browser right now
![image](https://user-images.githubusercontent.com/38470852/108845392-a87e3e00-75dd-11eb-8fb6-2c46c7e2ddc2.png)

**Comment by skypan** [comment]
i haved solve it , the map must set antialias = true
the code is :
`var map = new mapboxgl.Map({
			container: 'map',
			style: 'mapbox://styles/mapbox/dark-v9',
			center: origin,
			zoom: 17,
			pitch: 60,
			// 开启抗锯齿
			antialias: true
		});`
thank you very much again
