### ISSUE TITLE
How to focus and enlarge 3D objects after selecting them

### ISSUE THREAD

**Issue by liuyonghuaaihcw** [jscastro76/threebox#207]
**Threebox version**:

**Comment by jscastro76** [comment]
Please be a bit more specific on your question sharing what you have coded so far so then I can provide a proper answer.
If you want to focus on an object selected you will need to use one the the mapbox methods for centering the map (i.e `map,flyTo`) 
If you want to change the size on an object you will need to use `obj.set` method as described in the documentation.

**Comment by jscastro76** [comment]
@liuyonghuaaihcw can you clarify your question, describing it a bit better and/or adding the code you're stuck with?
