### ISSUE TITLE
about Building shadow

### ISSUE THREAD

**Issue by hahaxiaowai** [jscastro76/threebox#213]
**Threebox version**:

### Question
Hi！
I already know that building shadows cannot be used in 2.0,So I tried to change BuildingShadow.js.I changed this line of code and the shadow is loaded，But the shadow display is not correct,I have no ideas to solve this problem, can you provide a direction？Thanks!
``` js
// const source = this.map.style.sourceCaches['composite'];
const source = this.map.style._sourceCaches['other:composite'];
```
![shadow](https://user-images.githubusercontent.com/49934348/112952019-978d9300-916e-11eb-9cc8-b36d60e43106.jpg)

**Comment by jscastro76** [comment]
I have even received offers for paid work only in this feature... it's in the list of identified issues before moving to Mapbox 2.0 #146
Something is being wrongly calculated in the shader, I need to do a research on what are the changes in Mapbox 2.0 that affected this apart from the source and layer

**Comment by jscastro76** [comment]
Duplicated with #146
