### ISSUE TITLE
`tb.dispose()` doesn't work well.

### ISSUE THREAD

**Issue by DevArt002** [jscastro76/threebox#228]
Hi Jesus,

Thanks for publishing threebox-plugin. It's very interesting for me.
Actually, I integrated your plugin with my React project. But detected several issues.
Today, I am sharing 2 issues since they are terrible. Please review attached images which say the issues.

Thank you!

![warning](https://user-images.githubusercontent.com/52213952/114270628-1eb3f400-9a16-11eb-8f24-566f1aa47aa4.PNG)
![prev](https://user-images.githubusercontent.com/52213952/114270630-1fe52100-9a16-11eb-8f82-47daf5d215c3.PNG)

**Comment by jscastro76** [comment]
Hi @DevArt002, 
Thanks for reporting issues but please, follow the rules to receive help, time is precious for everyone.
First, only one problem per issue, if you have two problems, please open two different issues.
Second, if you have a template to report an issue, why did you remove it? The template force you to indicate version (there are 20 versions published) of the code/module you are using and add the code on how to repro it (I cannot debug pictures, sorry), that will help me to identify what’s producing the issue.
As soon as you complete the issues in that way I will provide a potential way to resolve them or I’ll fix them if they are bugs.
Thanks.!
