### ISSUE TITLE
`tb.dispose()` in dev mode not working.

### ISSUE THREAD

**Issue by DevArt002** [jscastro76/threebox#229]
According to your advice, I open issue again. 

I am using threebox-plugin for 3d visualization on mapbox. It is integrated with React SPA.
Whenever page is refreshed/reloaded or navigated to another page, `tb` should be disposed. 
When I refresh the page with `F5` or `CMD+R` manually, `tb.dispose()` works. But whenever the page is refreshed during React development, it doesn't work. 

Below I described code snippets:

Class that contains threebox-plugin implementation:
```
class ThreeboxController {
  ...
  dispose(): void {
    window.tb.dispose();
    window.tb = {};
  }
  ...
}
```
In react component:
```
useEffect(() => {
  return () => {
    threeboxController.dispose();
  };
}, []);
```
_(It means that threebox should be disposed whenever page is unmounted)_

In dev mode, whenever I change some code and save it, the React page is refreshed automatically. But it shows error:

Screenshots:
![preview](https://user-images.githubusercontent.com/52213952/114278580-2cc73c00-9a39-11eb-9294-8cab3e6efe9f.gif)

![dispose error](https://user-images.githubusercontent.com/52213952/114278290-c2fa6280-9a37-11eb-949e-cf5152cc0073.PNG)

**Comment by jscastro76** [comment]
I will investigate this one... it seems `scene.dispose` has been removed from THREE

**Comment by DevArt002** [comment]
Thank you @jscastro76

**Comment by jscastro76** [comment]
Found... Apparently `scene.dispose()` was removed in three.js r122, but the [migration guide](https://github.com/mrdoob/three.js/wiki/Migration-Guide#r121--r122).

Easy to solve... resolving it directly to include it in the next release v2.2.2. that I want to upload tomorrow.

**Comment by DevArt002** [comment]
Awesome! I am excited with **v2.2.2**.

**Comment by jscastro76** [comment]
Please @DevArt002 check if the new module v2.2.2 has solved your issue
