### ISSUE TITLE
Heatmap Generation on 3D Object

### ISSUE THREAD

**Issue by davidfungf** [jscastro76/threebox#238]
**Threebox version**:

### Question
I import a 3D object (fbx) successfully. 
![image](https://user-images.githubusercontent.com/3412715/115050703-9a2e0d80-9f0e-11eb-80e3-ace518aee069.png)

In order to show the temperature data distribution, how do I generate a heatmap on the surface of the buildings? Thanks.

**Comment by jscastro76** [comment]
This is not a Threebox-related question, it’s a Three.js question.

If each building is a different object and you have the temperature for each, you can use in Threebox the property `obj.color`, that will change the color of the full building (again, if each building is a different object). 

If all of those white buildings are a single FBX object, you’ll have a serious problem to deal with. If so, I’d recommend you to create a minimal reproducible example and post the question on stackoverflow.

**Comment by davidfungf** [comment]
Thank you for you advice. The color is changed by `obj.color`

![image](https://user-images.githubusercontent.com/3412715/115101294-5d493180-9f75-11eb-9515-2f26fc20c332.png)

I try to modify the code using THREE material but it returned "ReferenceError: geometry is not defined"

 ```
var options = {
         obj: './models/buildings.fbx', //model url
         type: 'fbx',
         scale: 0.3,
         units: 'meters',
         rotation: { x: 90, y: 270, z: 0 }, //default rotation
         anchor: 'center'
}

tb.loadObj(options, function (model) {
      let bldg = new THREE.Mesh(geometry, new THREE.MeshPhongMaterial({ color: 0x660000 }));
      bldg = model.setCoords(origin1);
     . ...
                        
```
