### ISSUE TITLE
model deep test

### ISSUE THREAD

**Issue by hahaxiaowai** [jscastro76/threebox#240]
**Threebox version**: 2.2.2

### Question
hi,Thanks for reading.
Recently I am trying a new version of threebox. When loading the model, if it is a small model, the building layer can successfully occlude the model.Deep test is useful But when I increase the model scale and pitch increase,the building layer cannot obscure the building model, Deep inspection failed.
Is it the problem I use？
![1](https://user-images.githubusercontent.com/49934348/116359043-e7747e00-a830-11eb-9f8f-408e10fbff2a.jpg)
![2](https://user-images.githubusercontent.com/49934348/116359058-ea6f6e80-a830-11eb-857a-4904049ee5e8.jpg)

**Comment by jscastro76** [comment]
I have never seen that behavior, could you provide a repro?

**Comment by hahaxiaowai** [comment]
I tested the current version and found that it is not a threebox problem，I changed the source code of mapbox, but I haven't found out what is affecting threebox.
Thanks for your answer, I will close this issues

**Comment by jscastro76** [comment]
Just FYI, I created today a demo trying to repro your issue... scaling a huge dinosaur in the museum fill-extrusions and it works properly no matter the size of the 3D object and the pitch
![image](https://user-images.githubusercontent.com/38470852/117545064-86189000-b024-11eb-828a-a05ad953e9ea.png)

**Comment by jscastro76** [comment]
Ah ok, all the examples are validated with [Mapbox 2.2.0](https://api.mapbox.com/mapbox-gl-js/v2.2.0/mapbox-gl.js)
