### ISSUE TITLE
Darken the raster layer with `realSunlight`

### ISSUE THREAD

**Issue by jscastro76** [jscastro76/threebox#244]
When `realSunlight: true` the lights simulate the sun light but the raster layers from the satellite style still illuminated, which makes the view inconsistent.
![image](https://user-images.githubusercontent.com/38470852/117466542-1ededb00-af53-11eb-9aec-efffab259a3a.png)

Ideally, the ground raster layer should be darkened based on sun altitude to get a more realistic effect. 

Analyze also the option to change it in other styles such as outdorr, light, dark

**Comment by jscastro76** [comment]
![image](https://user-images.githubusercontent.com/38470852/117466973-8eed6100-af53-11eb-9f12-649b6b68774f.png)

**Comment by mobeen-asghar** [comment]
@jscastro76 
Thank you for your prompt response. I understand it's a feature, but there should be an option to enable/disable it. As you can see in Picture 1, I am using 3D buildings with a custom 3D model. When I turn this feature on, it darkens the 3D buildings. Please take this into consideration. Thanks again for the solution.

PIC 1:
![pic1](https://github.com/jscastro76/threebox/assets/116583479/43135a9e-3585-462f-af6e-2ec749d6f7ba)

PIC 2: For reference
![pic2](https://github.com/jscastro76/threebox/assets/116583479/87ffd37e-f7d6-4313-aad1-87359a9bc4b8)
