### ISSUE TITLE
threebox_plugin_dist_threebox__WEBPACK_IMPORTED_MODULE_4__.Threebox is not a constructor

### ISSUE THREAD

**Issue by notflip** [jscastro76/threebox#246]
**Describe the bug**
When instantiating the plugin using the npm method I receive the following error
`: threebox_plugin_dist_threebox__WEBPACK_IMPORTED_MODULE_4__.Threebox is not a constructor`

**To Reproduce**
```
import { Threebox } from 'threebox-plugin/dist/threebox';
window.tb = new Threebox();
```

I'm using webpack to compile ES6 to JS.

**Comment by jscastro76** [comment]
Please check out previous issues in this topic #172, #178 
Depending the framework, wrapper or bundle you are consuming Threebox from, you could try with the following options:
Vue.js
```js
Option1: import { Threebox } from 'threebox-plugin'; //used to works directly
Option 2: import Threebox from 'threebox-plugin/dist/threebox'; 
```
React used to work well with this
```js
import { Threebox } from 'threebox-plugin';
```
Inline code when Threebox is rebundled
```js
import Threebox from './threebox-plugin/src/Threebox.js';
```
Do you have a repo to take a look at?

**Comment by notflip** [comment]
@jscastro76 It's working now using a normal import
`import 'threebox-plugin/dist/threebox';`

This plugin is great! Thanks

**Comment by jscastro76** [comment]
I’ll add that one as an alternative option!!! 
thanks for the feedback! glad to hear it’s helpful!

**Comment by jparish3** [comment]
for the record I can only use Option1 in Vue.js. I am not able to use the loader...getting this error:

loadObj.js?f767:100 Could not load model file: @/models/100_n_tryon.glb 
 SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at GLTFLoader.parse
