### ISSUE TITLE
can't get line by raycaster.

### ISSUE THREAD

**Issue by spirityy** [jscastro76/threebox#251]
**Describe the bug**

>  console.info(tb.queryRenderedFeatures(point))

can't get line by raycaster,Raycasting for LineSegments2 (and thus Line2) was added with R112.

**Comment by jscastro76** [comment]
Can you add the code for a repro? It's hard to know what's working wrong without code.

**Comment by spirityy** [comment]
`laneline.features.forEach(it => {
                    let lineGeometry = it.geometry.coordinates;
                    let line = window.tb.line({
                        geometry: lineGeometry,
                        width: 3,
                        color: 'steelblue'
                    });
                    window.tb.add(line);
                })`


` map.on('mousemove', (e) => {
                        console.info(tb.queryRenderedFeatures(e.point))
                    })`

**Comment by spirityy** [comment]
Let me change the question, how do I get  `tb.line` object with the mouse click?
