### ISSUE TITLE
Avoid overriding cursor behaviour

### ISSUE THREAD

**Issue by ondrej-vesely** [jscastro76/threebox#252]
It seems using Threebox overrides all cursor behaviour defined in Mapbox by overriding the element style of `.mapboxgl-canvas-container`. As a result cursor is forced to `default` unless specified otherwise during Threebox specific interactions.
This is especially frustrating when using something like mapbox-gl-draw and not getting any cursor feedback on when I'm hovering over features etc.

**Possible solutions?**

- use `this.getCanvasContainer().style.cursor = null;` instead of `this.getCanvasContainer().style.cursor = 'default';` ?

EDIT: Sorry for the Feature label, probably should be under Code Improvements.

**Comment by jscastro76** [comment]
@ondrej-vesely Thanks for opening the issue!
It’s ok with feature, no worries. Thanks for opening the issue, I’ll look for options that allows to define a default cursor. I’ll be back to you ASAP

**Comment by jscastro76** [comment]
you can use now the property `tb.defaultCursor` on map load event to define you favorite.
