### ISSUE TITLE
npm package not use

### ISSUE THREAD

**Issue by hahaxiaowai** [jscastro76/threebox#256]
**Threebox version**:lastest

### Question
Hi,I am coming again. Today I tried to use NPM Install Threebox-Plugin. But it doesn't work properly, can you help me to see where there is a problem, or this package cannot be used.
Error: _threebox.Threebox is not a constructor
This is sandcodebox:https://codesandbox.io/s/great-benz-nyy7o?file=/src/App.vue

**Comment by jscastro76** [comment]
Try this [Vue sample](https://codesandbox.io/s/great-firefly-qx9vo?file=/src/components/HelloWorld.vue)
```js
<template>
  <div id="map"></div>
</template>

<script>
import "mapbox-gl/dist/mapbox-gl.css";
import mapboxgl from "mapbox-gl";
import threebox from "threebox-plugin/dist/threebox";

export default {
  name: "helloworld",
  components: {},
  mounted() {
    this.initmap();
  },
  methods: {
    initmap() {
      mapboxgl.accessToken =
        "pk.eyJ1IjoiaGFoYXhpYW93YWkiLCJhIjoiY2szZTI4bWh2MWdwYzNucGRlcWgxMWg2aCJ9.ykCKZTiqQWql2XjNsOgTuQ";
      this.map = new mapboxgl.Map({
        container: "map",
        style: "mapbox://styles/mapbox/satellite-v9",
        zoom: 17,
        center: [-74.5, 40],
        antialias: true,
      }).on("style.load", () => {
        window.tb = new Threebox(
          this.map,
          this.map.getCanvas().getContext("webgl"),
          {
            defaultLights: true,
          }
        );

        this.map.addLayer({
          id: "custom_layer",
          type: "custom",
          renderingMode: "3d",
          onAdd: function () {
            // instantiate threebox

            //instantiate a red sphere and position it at the origin lnglat
            var sphere = window.tb
              .sphere({ color: "red", material: "MeshToonMaterial" })
              .setCoords([-74.5, 40]);
            // add sphere to the scene
            window.tb.add(sphere);
          },

          render: function () {
            window.tb.update();
          },
        });
      });
    },
  },
};
</script>

<style scoped>
#map {
  width: 100%;
  height: 100vh;
}
</style>

```

**Comment by hahaxiaowai** [comment]
It's working! Thanks
Do you consider reconstructing the entire threebox? I noticed that tb must be mounted on Window, which has a lot of limitations in usual use. There are many ways to write in the code. If I quote src/threebox.js directly, there will be a lot of errors.This is because I can't find tb

**Comment by jscastro76** [comment]
> It's working! Thanks
> Do you consider reconstructing the entire threebox? I noticed that tb must be mounted on Window, which has a lot of limitations in usual use. There are many ways to write in the code. If I quote src/threebox.js directly, there will be a lot of errors.This is because I can't find tb

No, I’m not thinking on reconstructing the entire Threebox, luckily this is an open source project MIT license your you can do it by yourself!
