### ISSUE TITLE
Unexpected text on map view -- "size(m): 4667.249 W, 4667.249 L, 23336.243 H"

### ISSUE THREAD

**Issue by DevArt002** [jscastro76/threebox#258]
Hi @jscastro76 

I am not sure if this issue is from threebox-plugin. I am using v2.2.2 for building one project. Sometimes I see unexpected text on map view after doing some actions. Below I shared the screenshot:
![image](https://user-images.githubusercontent.com/52213952/120797329-bdc60b00-c4f0-11eb-9a39-1be263e145b3.png)

Looking forward to hearing your advice. Thanks!

**Comment by jscastro76** [comment]
Hi @DevArt002
That’s the size of the object, you have selected an object and pressed SHIFT+S

**Comment by DevArt002** [comment]
Hi @jscastro76 
Thank you for letting me know. Well, I would be happy to know the best practice for disabling the text? Because I think I saw the text even when I didn't click SHIFT+S

**Comment by jscastro76** [comment]
It’s so specific (requires 2 interactions and enableSelectingObjects) that I didn’t add a deactivation variable. 
I’ll add it to the backlog.
Thanks for reporting

**Comment by DevArt002** [comment]
I really appreciate it!
