### ISSUE TITLE
gltf model not loading

### ISSUE THREAD

**Issue by pundirmr** [jscastro76/threebox#261]
When trying to load a gltf model getting following error :
Can we get support for draco gltf loader.

 **Error: THREE.GLTFLoader: No DRACOLoader instance provided.**

version : 2.2.3

**Comment by jscastro76** [comment]
This is a topic that was already evaluated and discussed [here](https://github.com/jscastro76/threebox/issues/117#issuecomment-747998263)
Long story short, no, DRACO is not in the roadmap as it implies to embed a bunch of extra libraries that will make Threebox grow importantly in size. I think [one of the forks of this project](https://github.com/murataka/threebox) already included DRACO, but using online libraries through `dracoLoader.setDecoderPath` which is an approach, but then the library wouldn't be anymore useful offline (which was one of my requirements from the very first day)
