### ISSUE TITLE
Cannot load Object 

### ISSUE THREAD

**Issue by picpic1979** [jscastro76/threebox#262]
Hello, 

I tried to use Threebox to load an object in React, I followed the doc from Mapbox to use Mapbox in React, i m not using react map gl, just mapboxgl, i followed your started sample that is not in react. I have this issue : 

src\components\Map.js
  Line 83:21:  'tb' is not defined  no-undef
  Line 85:25:  'tb' is not defined  no-undef
  Line 91:21:  'tb' is not defined  no-undef

this is my code

//map
import React, { useRef, useCallback, useEffect, useState, Fragment, useContext } from 'react';
import mapboxgl from '!mapbox-gl'; // eslint-disable-line import/no-webpack-loader-syntax
import { FirebaseContext } from './firebase';
import MapPopup from '../components/MapPopup';
import SideBar from './SideBar';
import { Threebox }  from '../../node_modules/threebox-plugin/dist/threebox';

mapboxgl.accessToken = 'pk.eyJ1IjoicGljcGljMTk3OSIsImEiOiJjazkwNno0NTAwYThhM2duNDl0ZmxqN3F6In0.cde4v5Pi0WMLUyHrNd5P-g';

const Map = () => {

    const firebaseContext = useContext(FirebaseContext);

    const mapContainer = useRef(null);
    const map = useRef(null);
    const [lng, setLng] = useState(-1.6214694296580212);
    const [lat, setLat] = useState(49.63349446077185);
    const [zoom, setZoom] = useState(12);
    const [batTitle, setbatTitle] = useState('Nom du batiment');

    //popup management
    const [popupVisibility, setPopUPVisibility] = useState('hidden');
    const [BatlayerToggle, SetBatLayerToggle] = useState('none');

    const [hovermarker, SethoverMarker] = useState(false);

    /////////////////////////////3DOBJECT///////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////////////////////////////////

    //Refresh map...............
    useEffect(() => {
       
        if (map.current) return; // initialize map only once

        map.current = new mapboxgl.Map({
        container: mapContainer.current,
        style: 'mapbox://styles/picpic1979/ckoe1ilwl1zbi19lknjci52kf',
        center: [lng, lat],
        zoom: zoom
        });

        //////////////////Source pour les markers

        var geojson = {
            "type": "FeatureCollection",
            "features": []
        };

        map.current.on('load', function () {

            ///////////////////////////////Object 3d test//////////////////

            var origin = [-1.6214579944290688,49.63359198600041];
            var model;

            map.current.addLayer({

                id: 'custom_layer',
                type: 'custom',
                renderingMode: '3d',   

                onAdd: function (map, mbxContext) {

                    window.tb = new Threebox(
                        map,
                        mbxContext,
                        { defaultLights: true }
                    );

                    var options = {
                        obj: '../models/gare.glb',
                        type: 'gltf',
                        scale: 100,
                        units: 'meters',
                        rotation: { x: 90, y: 0, z: 0 } //default rotation
                    }

                    tb.loadObj(options, function (model) {
                        model = model.setCoords(origin);
                        tb.add(model);
                    })

                },

                render: function (gl, matrix) {
                    tb.update();
                }

            });

            ///////////////////////////////

            map.current.addSource('batiments', {
                'type': 'geojson',
                'data': geojson
            });

            map.current.addLayer({
                'id': 'batimentsLayer',
                'type': 'circle',
                'layout': {
                    // Make the layer visible by default.
                    'visibility': BatlayerToggle,
                    },
                'source': 'batiments',
                'paint': {
                'circle-color': '#4264fb',
                'circle-radius': 10,
                'circle-stroke-width': 2,
                'circle-stroke-color': '#ffffff'
                }
            });

            var marker = {
                type: 'Feature',
                properties: { 'name':'empty'},
                geometry: {
                    type: 'Point',
                    coordinates: [49.632134192780065, -1.6220623309750013]
                    }
            };
              
            geojson.features.push(marker);

            map.current.getSource('batiments').setData(geojson);
            
        });

        map.current.on('click','batimentsLayer', function (e){       
   
            ///popup
            var coordinates = e.features[0].geometry.coordinates.slice();
             
            // Ensure that if the map is zoomed out such that multiple
            // copies of the feature are visible, the popup appears
            // over the copy being pointed to.
            while (Math.abs(e.lngLat.lng - coordinates[0]) > 180) {
            coordinates[0] += e.lngLat.lng > coordinates[0] ? 360 : -360;
            }

            const name = e.features[0].properties.name;
            
            var popup = new mapboxgl.Popup({ closeOnClick: true })
            .setLngLat(coordinates)
            .setHTML(
                "<div class='popuptitle' >"
                + name + 
                "</div>"
            )
            
            popup.on('open', function(e) {
            }); 
            
            popup.on('close', function(e) {    
             });
            
            popup.addTo(map.current);
        });

        // Change the cursor to a pointer when the mouse is over the places layer.
        map.current.on('mouseenter', 'batimentsLayer', function (e) {
            map.current.getCanvas().style.cursor = 'pointer';
            const name = e.features[0].properties.name;
            setbatTitle(name);
            SethoverMarker(true);
        });

            // Change it back to a pointer when it leaves.
        map.current.on('mouseleave', 'batimentsLayer', function (e) {
            map.current.getCanvas().style.cursor = '';
            const name = 'Selectionnez un batiment';
            setbatTitle(name);
            SethoverMarker(false);
        });

        //database recherche des batiments
        firebaseContext.db.collection("batiments")
        .onSnapshot((snapshot) => {
            snapshot.docChanges().forEach((change) => {                       
               
                if (change.type === "added") {                 

                    const {name,coordonate} = change.doc.data();       
                      
                    // Add a marker feature to your geojson object
                    var marker = {
                    type: 'Feature',
                    properties: { 'name':name },
                    geometry: {
                        type: 'Point',
                        coordinates: [coordonate._lat, coordonate._long]
                        }
                    };
                    
                    geojson.features.push(marker);

                    if(map.current.getSource('batiments'))//en cas de load initial bien exclure ....
                    map.current.getSource('batiments').setData(geojson);
                    
                }
                if (change.type === "modified") {

                    console.log("batiment modifié : ", change.doc.data());
                    
                    const {name,coordonate} = change.doc.data();

                    var marker = {
                        type: 'Feature',
                        properties: { 'name':name },
                        geometry: {
                            type: 'Point',
                            coordinates: [coordonate._lat, coordonate._long]
                            }
                        };
                      
                        geojson.features.map(  marker => 
                        {
                            if(marker.properties.name == name)
                            {
                                marker.properties.name = name;
                                marker.geometry.coordinates = [coordonate._lat, coordonate._long];
                            }
                        }
                    );

                    map.current.getSource('batiments').setData(geojson);

                }
                if (change.type === "removed") {

                    console.log("batiment supprimé : ", change.doc.data());       

                    const {name,coordonate} = change.doc.data();
                   
                    geojson.features.map(  marker => 
                    {
                        const indexofMarker = (marker) => marker.properties.name ==  name;

                        const id = geojson.features.findIndex(indexofMarker)

                        if(marker.properties.name == name)
                        {
                            geojson.features.splice(id,1);
                        }
                    });

                    map.current.getSource('batiments').setData(geojson);

                }
            });
        });

    });

    useEffect(() => {
        if (!map.current) return; // wait for map to initialize

           
        if(!hovermarker)
        {
            setPopUPVisibility('hidden');
        }
        else
        {
            setPopUPVisibility('visible');
        }
    

        map.current.on('move', () => {
            setLng(map.current.getCenter().lng.toFixed(4));
            setLat(map.current.getCenter().lat.toFixed(4));
            setZoom(map.current.getZoom().toFixed(2));
        });

        if(map.current.getSource('batiments'))
        map.current.setLayoutProperty('batimentsLayer','visibility',BatlayerToggle)
    });

    /////////////////////////////////////////////////////////////////////////////////////////////

    return (
        <Fragment>
            <div ref={mapContainer} className="map-container" />
            <SideBar onClick={ () => SetBatLayerToggle(
                ( BatlayerToggle == 'visible') ? 'none' : 'visible'
            )}
            ></SideBar>
            <MapPopup visibility={popupVisibility} Title={batTitle} bottom="100px" right="50px"></MapPopup>
        </Fragment>
    );
};

export default Map;

I really missing some thing, have you any sample with react intégration like this ?

Thanks

**Comment by jscastro76** [comment]
Do you have a minimum reproducible example?

**Comment by picpic1979** [comment]
No i just have my project that is small for the moment. I will try a minimum intégration with just a 3d model.

**Comment by picpic1979** [comment]
Hi, just finish a short minimal sample and i have the same error

src\Map.js
  Line 53:6:  'tb' is not defined  no-undef
  Line 55:7:  'tb' is not defined  no-undef
  Line 60:6:  'tb' is not defined  no-undef

Search for the keywords to learn more about each error.

My code

`import React, { useRef, useEffect, useState } from 'react';
import mapboxgl from '!mapbox-gl'; // eslint-disable-line import/no-webpack-loader-syntax
import { Threebox } from 'threebox-plugin/dist/threebox'; 
 

mapboxgl.accessToken = 'pk.eyJ1IjoicGljcGljMTk3OSIsImEiOiJjazkwNno0NTAwYThhM2duNDl0ZmxqN3F6In0.cde4v5Pi0WMLUyHrNd5P-g';

const Map = () => {

    const mapContainer = useRef(null);
    const map = useRef(null);
    const [lng, setLng] = useState(-1.6215116363994757);
    const [lat, setLat] = useState(49.63364757742455);
    const [zoom, setZoom] = useState(18);

    //init de la map
    useEffect(() => {

        if (map.current) return; // initialize map only once

        map.current = new mapboxgl.Map({
        container: mapContainer.current,
        style: 'mapbox://styles/picpic1979/ckoe1ilwl1zbi19lknjci52kf',
        center: [lng, lat],
        zoom: zoom
        });

        var origin = [49.63364757742455, -1.6215116363994757];
		var soldier;

        map.current.on('style.load', function () {

			map.current.addLayer({
				id: 'custom_layer',
				type: 'custom',
				renderingMode: '3d',
				onAdd: function (map, mbxContext) {

					window.tb = new Threebox(
						map,
						mbxContext,
						{ defaultLights: true }
					);

					var options = {
						obj: './models/gare.glb',
						type: 'gltf',
						scale: 1,
						units: 'meters',
						rotation: { x: 90, y: 0, z: 0 } //default rotation
					}

					tb.loadObj(options, function (model) {
						soldier = model.setCoords(origin);
						tb.add(soldier);
					})

				},
				render: function (gl, matrix) {
					tb.update();
				}
			});
		})



    });

    //update des coordonnées
    useEffect(() => {
        if (!map.current) return; // wait for map to initialize

        map.current.on('move', () => {
        setLng(map.current.getCenter().lng.toFixed(4));
        setLat(map.current.getCenter().lat.toFixed(4));
        setZoom(map.current.getZoom().toFixed(2));
        });



    })


    return (
        <div>
            <div className="sidebar">
                Longitude: {lng} | Latitude: {lat} | Zoom: {zoom}
            </div>
            <div ref={mapContainer} className="map-container" />
        </div>
    );
};

export default Map;`

Give you the sample that uploading right now...

https://drive.google.com/drive/folders/1cg_Z6y15x9GMBb2X0Uxz4MplliB4VeWG?usp=sharing

**Comment by jscastro76** [comment]
This is an Open Source project under MIT license, so there’s no SLA or support desktop. Please provide a functional Codepen or a Fiddle example where I can take a look at, otherwise I cannot help

**Comment by picpic1979** [comment]
Sorry, i finally find the problem but i really don't understand why i have to do that, i change my import from
import { Threebox } from '../../node_modules/threebox-plugin/dist/threebox';
to 
import { Threebox }  from '../../node_modules/threebox-plugin/main.js';
