### ISSUE TITLE
models do not load from examples

### ISSUE THREAD

**Issue by jparish3** [jscastro76/threebox#265]
from /threebox/examples/06-object3d.html:

Uncaught ReferenceError: m is not defined
    at Object.onError (threebox.js:3984)
    at XMLHttpRequest.<anonymous> (threebox.js:18798)

**Comment by jscastro76** [comment]
I'm running the example right now with the latest bits?
![image](https://user-images.githubusercontent.com/38470852/124968004-65b98180-e025-11eb-8eec-2c62d6861dc1.png)

**Comment by jscastro76** [comment]
BTW that `m` is definitely undefined, I'm changing it for `error.stack`, but the example as is, works.
Are you modifying the example to load other models?

**Comment by jscastro76** [comment]
I have created new builds, can you repeat your test?? I'm curious to know the `error.stack` in your console

**Comment by jparish3** [comment]
After updating I get this warning: No material file found undefined
(anonymous) @ threebox.js:3984

**Comment by jparish3** [comment]
regarding our first question: I am running the examples as is, without modification. There only seems to be issues with examples that load model files

**Comment by jscastro76** [comment]
Are you initializing node server first? Files are loaded by relative url path so you need to initiate server.js

**Comment by jparish3** [comment]
I guess not is that an npm command ?

**Comment by jparish3** [comment]
I tried npm start & npm run all, then ran the example but still get the warning and no model load (map only)

**Comment by jparish3** [comment]
When I run from VS Code using live server the models load fine. I did not realize that was required...the other examples with extrusions (8 & 18) work directly in the browser. I appreciate your quick response and the extensive documentation.

**Comment by jscastro76** [comment]
> When I run from VS Code using live server the models load fine. I did not realize that was required...the other examples with extrusions (8 & 18) work directly in the browser. I appreciate your quick response and the extensive documentation.

The examples with extrusions create objects, do not execute `tb.loadObj` so no model is requested through url
Good you solved it
