### ISSUE TITLE
Mesh have jitter when moving the map

### ISSUE THREAD

**Issue by mohong** [jscastro76/threebox#267]
I implemented a flow effect using threejs:
![](https://github.com/mohong/line-example/blob/main/screenshot/threejs-effect.png?raw=true)
[threejs code](./threejs.html), [preview](http://arthas.com.cn/line-example/threejs.html)

Use the same method to achieve the same effect in threebox:
![](https://github.com/mohong/line-example/blob/main/screenshot/threebox-effect.png?raw=true)
[threebox code](./threebox.html), [preview](http://arthas.com.cn/line-example/threebox.html),
but it has a jiggle when moving the map:
![](https://github.com/mohong/line-example/blob/main/screenshot/GIF.gif?raw=true)
Why is that? Is there a better way to do it?

Thanks!

**Comment by jscastro76** [comment]
Apparently it seems an inherited issue from mapbox managing long decimal numbers.. 
I experienced a similar issue when building the extrusions feature (#125). They way I found to solve it was to reduce de precision decimals of the objects (#127).
