### ISSUE TITLE
large dataset needs to be rendered as 3d models

### ISSUE THREAD

**Issue by spirityy** [jscastro76/threebox#269]
When the length of the data is <1000 , it's fine. 
When the data reaches 5000, the experience becomes very laggy.
But the vast majority of the models are not in the field of view. 
How to handle this situation?

**Comment by jscastro76** [comment]
You should manage the logic to load or not objects that are out of the map
Bounding Box or zoom level in the page/scripts for loading. In one of my projects I drove this through two functions, on the moveend event of the map checking what needs to be loaded or removed from the dataset. You can also create a recursive method with pages to load the objects in blocks of 100 or so to make it more fluent
