### ISSUE TITLE
Why the value of WORLD_SIZE is 1024000

### ISSUE THREAD

**Issue by sknightq** [jscastro76/threebox#273]
`const WORLD_SIZE = 1024000; //TILE_SIZE * 2000` in this [file](https://github.com/jscastro76/threebox/blob/master/src/utils/constants.js)  

It's maybe a ridiculous question. I want to know why the value of WORLD_SIZE is 1024000. Because I'm learning how to convert Mector coordinates to pixel points.

**As I know, the Mapbox's tile size is 512*512 or 256 * 256, default is 512 * 512. And where is 2000 from ?** 

 It's confusing me a few days.

Thanks for anyone can reply me.

**Comment by jscastro76** [comment]
It's the number of tiles horizontally (2000) multiplied by its size (512) at maximum detail. It's needed for basic positioning calculations

**Comment by LuckDogHu** [comment]
Why is the number of horizontal tiles 2000 instead of 2^zoom

**Comment by jscastro76** [comment]
> Why is the number of horizontal tiles 2000 instead of 2^zoom

Because it's not calculating the number of tiles at a concrete zoom level but the maximum number of tiles horizontally by its pixels, so a world as 1024000 pixels at 22 zoom level. It's basic to be used in the calculations
