### ISSUE TITLE
addHelp() on obj puts the "arrow" in a wierd spot

### ISSUE THREAD

**Issue by Philip2809** [jscastro76/threebox#276]
**Describe the bug**
When adding a "help", with addHelp(), the little "arrow" is in the wrong place.
![image](https://user-images.githubusercontent.com/51290462/130859271-027d6be2-f765-4124-8d35-cae2fd689f8e.png)
~~Also, is it possible to add html code to the popup?~~
I looked at the code and saw the "help" or the text in there sets the innerHTML

**To Reproduce**
doing this in onAdd();
`obj.addHelp("test", undefined, true);` // "test" is the text, undefined I put in there so i can place true to the mapboxstyle, as I don't understand what it is for

**Expected behavior**
![image](https://user-images.githubusercontent.com/51290462/130859351-b23b060f-50c4-411d-bded-ea4fd41c685d.png)
image from: https://stackoverflow.com/questions/65644945/threebox-tooltip-in-3d-models

**Relevant Code or Code Sandbox**
I was trying to set up a codepen, but I was not able to, getting syntacs errors, if I get one up and it shows the same error as I get, I will add it to the issue. 

**Console Results**
No console output

**Comment by jscastro76** [comment]
Again, please, review the documentation and the examples, if you want to use mapbox-like popups, you need to add the css that is in the 20 examples. 
```html
<link href="../dist/threebox.css" rel="stylesheet" />
```
