### ISSUE TITLE
tb.camera.quaternion always is zero. not correct

### ISSUE THREAD

**Issue by hong4k** [jscastro76/threebox#277]
to make Object3D face Camera，in Threejs, we use the following code

`object3d.quaternion.copy(camera.quaternion)`

but in threebox, tb.camera.quaternion always is zero

**Comment by jscastro76** [comment]
Without a minimum reproducible example is hard to help.
The camera (threejs camera) you're looking for is in `tb.camera`, but Mapbox camera is the one that controls the view, threejs camera is automatically synced on every move. If you what the object rotates to the camera view, you'll need to implement a handler for mapbox camera with....
```js
 tb.map.on('move', function () {
            //here you'll need to rotate all the objects from tb.world.children
        })
```

**Comment by hong4k** [comment]
I had try ,but still not as expected. 

Is there any way to calculate tb.camera.quaternion? use mapbox-gl  FreeCamera api?
I'm not very clear about the principle of conversion. If you have time to help take a look, 
thank you very much.
