### ISSUE TITLE
How do I detect a click on a obj added with loadObj?

### ISSUE THREAD

**Issue by Philip2809** [jscastro76/threebox#278]
**Threebox version**: 2.2.4

### Question
How do I detect when the user clicks on a object, an obj, not a fill-extrusion an obj added with tb.loadObj()? Am I missing something I can't seem to get it working, also I have another problem but I think that is more of a bug then a question, the map goes white when I hide/show objects from tb.world.children, but I will open a more detailed bug report about that.

**Comment by jscastro76** [comment]
Please, [read the documentation](https://github.com/jscastro76/threebox/blob/master/docs/Threebox.md#loadobj) on how to add an event listener to a 3D object and activate the selection with `enableSelectingObjects`, and check the examples
```js
	tb.loadObj(options, function (model) {

		soldier = model.setCoords(origin);

		soldier.addEventListener('SelectedChange', onSelectedChange, false);
		soldier.addEventListener('Wireframed', onWireframed, false);
		soldier.addEventListener('IsPlayingChanged', onIsPlayingChanged, false);
		soldier.addEventListener('ObjectDragged', onDraggedObject, false);
		soldier.addEventListener('ObjectMouseOver', onObjectMouseOver, false);
		soldier.addEventListener('ObjectMouseOut', onObjectMouseOut, false);

		tb.add(soldier);
	})

function onSelectedChange(e) {
	let selected = e.detail.selected; //we get if the object is selected after the event
	//if selected
	if (selected) {
		selectedObject = e.detail; 
		//do whatever
	}
}
```

**Comment by jscastro76** [comment]
@Philip2809, I think you have an issue with the scope where `this.onSelectedChange` is, because the event listener works in every single example provided (you only need to check any example and add it) and other projects using this plugin, including some in production.
I don't pretend you post your code in GitHub, but as said, unless you can provide a minimal reproducible example, I cannot help you to diagnose what is wrong in your code.

**Comment by Philip2809** [comment]
Hi, I think the problem is with the "enableSelectingObjects" when initalizing, I was trying to made a code playground and found this: https://codesandbox.io/s/sweet-kirch-q2iy9
Here it looks like this:
And here you get this box around it when selecting, in my code you don't, what could I be initalizing wrong?
How it looks for me:
https://user-images.githubusercontent.com/51290462/131579799-9cab614f-f43c-49e2-9f16-7adfa84e495f.mp4

How it should look:

https://user-images.githubusercontent.com/51290462/131579809-2c1786f4-c413-4647-81f7-e71761d450d1.mp4
or look at the codesandbox.io

How I initalize:
I create the map on: `ngAfterViewInit`
then I create the mapbox map and on 'load' I do:
```
(window as any).tb = new Threebox(this.map, this.map.getCanvas().getContext("webgl"), {defaultLights: true, enableSelectingObjects: true});
(window as any).tb.update();
```
Then I add the 3d buildings how mapbox does in their tutorial, Am I missing something?

I found a workaround to this by using `tb.queryRenderedFeatures,` so it is no longer the biggest deal ever but I am just curios why stuff is not working.

**Comment by jscastro76** [comment]
Honestly, I don't really know what is the issue you are having, but in less than 2 minutes, [this works](https://codesandbox.io/s/ecstatic-cohen-oidms?file=/src/index.js:0-1526):

```js
import mapboxgl from "mapbox-gl";
import "threebox-plugin/dist/threebox";
import "./styles.css";

const Threebox = window.Threebox;
mapboxgl.accessToken =
  "pk.eyJ1IjoiYm93ZW43IiwiYSI6ImNrbWxuZWllcDB2N3EycGxzeWZpbWw0MTcifQ.35kpoZMDgIG-xVK7CqAJdg";
const origin = [13.183444499597574, 55.71892456947439];

const map = new mapboxgl.Map({
  container: "map",
  style: "mapbox://styles/mapbox/light-v9",
  center: origin,
  pitch: 45,
  zoom: 17.5
});

const tb = (window.tb = new Threebox(map, map.getCanvas().getContext("webgl"), {
  defaultLights: true,
  enableSelectingObjects: true //change this to false to disable 3D objects selection
  // change this to false to disable default tooltips on fill-extrusion and 3D models
}));

map.on("style.load", function () {
  const options = {
    id: "123123",
    type: "gltf",
    obj:
      "https://uploads.codesandbox.io/uploads/user/616f82ed-df4d-4c3d-bb66-0f2f7c5626d2/I5J1-human_2.glb",
    scale: 1,
    units: "scene",
    anchor: "center",
    rotation: { x: 90, y: 90, z: 0 }
  };

  tb.loadObj(options, (model) => {
    console.log("loaded object");
    const obj = model.setCoords(origin);
    obj.addEventListener("SelectedChange", onSelectedChange, false);
    tb.add(obj);
  });

  map.addLayer({
    id: "custom_layer",
    type: "custom",
    render: function (gl, matrix) {
      tb.update();
    }
  });

  function onSelectedChange(e) {
    let selected = e.detail.selected; //we get if the object is selected after the event
    //if selected
    console.log("selected? " + selected);
  }
});
```
![image](https://user-images.githubusercontent.com/38470852/131661269-e9387497-fbfb-4a09-873a-33b27861ac86.png)
