### ISSUE TITLE
Map goes into "white space" when doing obj.visibility until I click on the map container

### ISSUE THREAD

**Issue by Philip2809** [jscastro76/threebox#279]
**Describe the bug**
Map goes white when setting `obj.visibility`, until I click on the map container, see video below!

**To Reproduce**
I add a obj with loadObj, it is an glb. I add it like describes except I don't add a new layer, because It works fine without it, as far as I can see, when trying to hide/show the layer that added the threebox objs nothing happened so I decided to remove them for now, if I am doing that wrong, please tell me, but adding layers drags the performance down, then when I change the `obj.visibility` and update the map goes white until I click on it, see video below.

**Expected behavior**
Same as now except for the white space.

**Relevant Code or Code Sandbox**
As stated before I add an obj then run this:
```
    for (const obj of tb.world.children) { // loop through tb objects
      if (obj.userData.layer === layer) { // if that is the obj i am looking for
        obj.visibility = show; // set the visibility to true / false
      }
    }
    tb.update(); // update tb
```

**Console Results**
No console output

**Screenshots**
https://user-images.githubusercontent.com/51290462/131465679-21981ce6-e0c5-418a-af50-590e652eff51.mp4

-[Version [2.2.4]

**Comment by jscastro76** [comment]
Without having your a minimum reproducible example I cannot help too much, I don't know where you are updating the map.
Your `tb.update` is repainting 3D objects, but out of a mapbox rendering trigger. If you want to repaint the map, you'll need to set `map.repaint = true` 
```js
tb.update();
map.repaint = true;
```
