### ISSUE TITLE
Doing obj.set(coords) does not set the coords while obj.setCoords does!

### ISSUE THREAD

**Issue by Philip2809** [jscastro76/threebox#280]
**Describe the bug**
Doing obj.set({coords: [lon, lat, height]}) does not set the coords for my, its only setting the "rotation" option. If I am doing obj.setCoords([lon, lat, height]) it works without a problem but I can't animate it like that.

**Expected behavior**
obj.set({coords: [lon, lat, height]}) should set the coords.

**Relevant Code or Code Sandbox**
```
const options = {
    coords: [this.longitude, this.latitude, heightOfSentFloor],
    rotation: {z: (-bearing)+90}
}
obj.set(options);
```
this sets the rotaion but not the coords.

**Console Results**
No console output

**Screenshots**
The green marker that is rotating should move to the green circles!
https://user-images.githubusercontent.com/51290462/132121098-7769c2a8-9820-42b5-9ede-969cf038b190.mp4

Best regards
Philip Magyar

**Comment by jscastro76** [comment]
Hi @Philip2809 
As this is your 5th issue opened in a few days, not being bugs any of them, I just want to clarify some terms of use of this repo for better mutual understanding. My time is limited, I guess as yours, and I consider your time at lease as precious as mine. 

This is an open source project under MIT license, which gives you a lot of benefits and rights, one of them is that you can open issues, but this is not a Support desktop with an SLA, for me this started as a simple hobby project contributing to OS community, that I have used (and still) in production environments. 

Having said so, and as said in all the other issues, just copying 2 lines of code is not enough to know what is not working properly in your code, you have variables being set, I guess you have a loop... and anything can be wrong. 

Second, [if you read the documentation of the method `obj.set`](https://github.com/jscastro76/threebox/blob/master/docs/Threebox.md#set) you'll see there are different params for animations (`duration > 0`) and without animations (`duration == 0`, undefined in your case). If you don't use animations, the param must be called `position`. 

Please, next time, read the documentation and in case it is wrong let me know and I'll fix it. Then if you find any issue of bug (that surely will happen), please provide a minimal reproducible example in fiddle, codepen or any other code sandbox of your preference that I can take a look at and help you when I have spare time.

Best Regards,
J
