### ISSUE TITLE
使用extrusion方法创建面，当我使用geojson类型的点坐标时，位置是错误的，并没有把面绘制到正确的经纬度位置

### ISSUE THREAD

**Issue by ycsgis** [jscastro76/threebox#281]
let mesh = tb.extrusion({
        coordinates: [polygon],
        materials: [material, material2],
        height:400000,
        geometryOptions: { depth: 20, steps: 1, bevelEnabled: true, bevelThickness: 2, bevelSize: 4, bevelSegments: 1 },
 
    });

我的polygon变量长这样：[[120,30],[120,30]]

**Comment by jscastro76** [comment]
Sorry, I don't speak chinese, but as long as I can understand from bing translator, your code includes only 2 points with the same position. A polygon requires at least 3 points (not in threebox, in geometry).
Please check the code of the [extrusion example](https://github.com/jscastro76/threebox/blob/master/examples/18-extrusions.html) where there are complex polygons including some with holes, and you can check the data array definition.
