### ISSUE TITLE
Render the model, checkbox mismatch

### ISSUE THREAD

**Issue by Dongsheng-Zhang** [jscastro76/threebox#283]
Hi, may I ask, when adding the 3D model, THE rotation and adjustment were made to the model, and then enableSelectingObjects was turned on. The actual check box did not conform to the model, what should I do? Looking forward to your reply

**Comment by jscastro76** [comment]
Can you add an image to understand better your issue??

**Comment by Dongsheng-Zhang** [comment]
![20210927160901](https://user-images.githubusercontent.com/22702908/134869605-7edcf9cd-3646-478e-a819-409de52b3837.png)

**Comment by Dongsheng-Zhang** [comment]
When initializing, add the model, rotate it, float the mouse around, and show the maximum border expected to align with the model

**Comment by Dongsheng-Zhang** [comment]
![20210927161848](https://user-images.githubusercontent.com/22702908/134870862-8cd182e2-6cc6-4b38-a7e6-b99105d5f1f3.png)
I don't know if I set it up right

**Comment by jscastro76** [comment]
Now I understand!. This is due to the fact that the three.js bounding boxes are axes oriented (AAOO)
What I recommend is to rotate the model always to the north for default position using the init param options, then use `model.setRotation(rotationZ);` to rotate the model only in 3D z axis (vertical). That will keep the box always aligned to the size of the object

**Comment by Dongsheng-Zhang** [comment]
Thank you very much for your reply. My problem can be solved. Originally, IT needs to be written in model instead of option.
In addition, I would like to ask another question. When using SelectedChange to change the position of the model, the check box is still in the original position. How should I change this problem
![20210927164834](https://user-images.githubusercontent.com/22702908/134875702-e22baf51-8c9d-47f7-a34d-53f82f4e84c7.png)

**Comment by jscastro76** [comment]
This is a different issue. To avoid mixing topics, we close this one as you were able to solve it
