### ISSUE TITLE
Questions about setRotation

### ISSUE THREAD

**Issue by Dongsheng-Zhang** [jscastro76/threebox#285]
Hi, MAY I ask that I use setRotation, a black line will be displayed when the mouse is selected, but there is no setRotation, looking forward to your reply
![20210928094422](https://user-images.githubusercontent.com/22702908/135009436-37430bf4-b7b5-4ea2-a797-0a54f178d6cb.png)

**Comment by jscastro76** [comment]
Please provide a Minimum Reproducible Example on your preferred code sandbox (fiddle, codepen...), I cannot debug an image.
