### ISSUE TITLE
Missing THREE in sphere.js

### ISSUE THREAD

**Issue by wwkb123** [jscastro76/threebox#286]
**Describe the bug**
I'm using React with the npm threebox-plugin, I tried the example 04-mercator.html, and keep getting error messages of THREE is not defined in sphere.js. I then looked at the source code of other Object3D files, like tube.js, seems they all have a line of defining THREE.
const THREE = require("../three.js");
I tried adding this line to sphere.js, and it solves the problem.

**To Reproduce**
1. in React component, import { Threebox } from "threebox-plugin"; 
2. copy the code from 04-mercator.html
3. run the react frontend
4. should see an error saying THREE is not defined

**Expected behavior**
the webpage should show what exactly shown in the 04-mercator.html example, i.e. showing 100 spheres on the map

**Relevant Code or Code Sandbox**
the variable THREE seems is not defined in the code. it seems simply adding 
const THREE = require("../three.js"); 
can solve the problem

**Console Results**
<img width="746" alt="Screen Shot 2021-09-28 at 12 58 37 PM" src="https://user-images.githubusercontent.com/18336646/135132138-914e5cb7-572f-499e-a3a8-4baec01e2037.png">

**Screenshots**
<img width="1095" alt="Screen Shot 2021-09-28 at 12 57 28 PM" src="https://user-images.githubusercontent.com/18336646/135132031-9478cb39-1539-4cc0-938f-23891bd3799d.png">

THREE is not defined
<img width="930" alt="Screen Shot 2021-09-28 at 12 41 05 PM" src="https://user-images.githubusercontent.com/18336646/135131542-211933f6-dc44-473b-918e-45c24f3a7fee.png">

While it's defined in some other files
<img width="753" alt="Screen Shot 2021-09-28 at 12 55 00 PM" src="https://user-images.githubusercontent.com/18336646/135131664-208ff683-6f2c-4485-834b-aec297fbcdd3.png">

- [Version 2.2.4]

**Additional context**
Sorry this is my first time posting an issue on GitHub, let me know if you need more information

**Comment by jscastro76** [comment]
Let me take a look to it and test it, but at first sight it seems you’re right and when I replaced geometries by buffer geometries this should have been added.

**Comment by jscastro76** [comment]
Solved
