### ISSUE TITLE
Updating to Three.js r132

### ISSUE THREAD

**Issue by citizenrusty** [jscastro76/threebox#287]

**Comment by citizenrusty** [comment]
I'm guessing it's a huge overhaul to update Threebox to use a newer version of Three.js. I've gone through all the examples of what Threebox can do, and it is everything I want. It's quite impressive!

The only problem is that my designs require materials that are both `"alphaMode":"BLEND"` and `"doubleSided":true`.

It seems that these properties combined together cause render issues in the older versions of Three, but it has been fixed since Three.js r130. Here is a preview. 
<img width="1214" alt="comparison" src="https://user-images.githubusercontent.com/86851189/135173726-51b209de-1f5f-4336-a82c-893f595a6940.png">
.

**Comment by jscastro76** [comment]
In the past, the update to some Three.js versions were painful, we were stuck in 117 for almost half a year until they solved some bugs affecting Threebox and Mapbox interaction.
As I have other pending issues to test, I’ll take a look to this update, but it requires to do an intensive testing

**Comment by jscastro76** [comment]
Just FYI... After a quick test... this change requires to update also all the loaders, and there's a change in Threejs that affects the `lineGeometry` so it will require a bit of work to update the full version.

**Comment by citizenrusty** [comment]
Thank you for the reply @jscastro76. It sounds like a big project. For now, I'll do a 3d-design hack. By duplicating my model and inverting the normals on the duplicate, that basically gives me a similar result as if I were rendering double-sided faces, without rendering double-sided faces. And again, great job on Threebox.

**Comment by jscastro76** [comment]
- [ ] update three.js main bundle
- [ ] update loaderes(FBX, GLTF, MTL with changes for url null, OBJ, Collada)
- [ ] Update Line, Line2, LineGeometry, LineSegmentGeometry, Wireframe, WireframeGeometry2, LineMaterial, LineSegments
- [ ] Update CSS2DRenderer, CSS2DObject including the changes for cache
- [ ] Test 21 examples

**Comment by jscastro76** [comment]
Thanks @citizenrusty for your feedback, now the code is updated to Threej.js latest version (r132). 
It'll be available as npm module tomorrow.
