### ISSUE TITLE
A way to control the camera separately from the Mapbox controls

### ISSUE THREAD

**Issue by citizenrusty** [jscastro76/threebox#288]
https://user-images.githubusercontent.com/86851189/135343040-1956e948-d545-4268-92c4-182148180293.mp4

In the past, I created many pre-rendered animations, using the GeoLayers plugin to embed Mapbox into After Effects. In this process, I learned a lot about camera moves. I'm now trying to recreate these camera moves in javascript, to dynamically generate them at any latitude/longitude I define as the world origin.

I understand that ThreeBox uses the `CameraSync.js` to mimic the MapBox camera, so you control the camera using Mapbox values. I also understand you can create animations with the `map.flyTo` command.

But I was hoping to simulate camera moves that are more cinematic, potentially using Tween.js to control the position, rotation, and `lookAt` point of a camera. I see that this Threebox fork does allow me to control the POV, which is amazingly helpful. But the Mapbox controls really cannot achieve what I want. They're limited to the position, rotation, and scale of the 3d World.

Is there a way to control a 3d camera classically, and have the MapBox matrix respond to that? The pitch and bearing could even be set to zero for this. I want to do things like:
1) show the perspective looking upward from the ground
2) rotate a camera on its own axis while moving it forward
3) have a camera move its position in a straight line, but stay locked on a target (which has a much more beautiful result than rotating the bearing or pitch of the map).

Here's an example of a video I made using Geolayers inside of After Effects, controlling a 2-node camera. I suppose there is some complex matrix math to be able to have MapBox values adjusted to match adjustments to a 3d camera. Any thoughts or advice? Is it even theoretically possible?

**Comment by citizenrusty** [comment]
I guess what I was looking for is part of the Mapbox FreeCamera API https://docs.mapbox.com/mapbox-gl-js/example/free-camera-point/

**Comment by jscastro76** [comment]
> I guess what I was looking for is part of the Mapbox FreeCamera API https://docs.mapbox.com/mapbox-gl-js/example/free-camera-point/

Yes, what you’re looking for is part of Free Camera
