### ISSUE TITLE
Mapbox mouse cursor style does not change once Threebox is initialized

### ISSUE THREAD

**Issue by John2397** [jscastro76/threebox#291]
On [this Mapbox example ](https://docs.mapbox.com/mapbox-gl-js/example/popup-on-click/) the mouse style is changed from cursor to pointer, when it is over the 'places' layer, by using:
```
map.on('mouseenter', 'places', () => {
      map.getCanvas().style.cursor = 'pointer';
});
```

I took the above example and just added threebox and initialized the `Threebox` object (under `map` initialization):

```
    window.tb = new Threebox(
        map,
        map.getCanvas().getContext('webgl'),
        {
            defaultLights: false,
            enableSelectingFeatures: false, //change this to false to disable fill-extrusion features selection
            enableSelectingObjects: false, //change this to false to disable 3D objects selection
            enableDraggingObjects: false, //change this to false to disable 3D objects drag & move once selected
            enableRotatingObjects: false, //change this to false to disable 3D objects rotation once selected
            enableTooltips: false, // change this to false to disable default tooltips on fill-extrusion and 3D models
            outlinePass: false
        }
    );
```

Once adding the above initialization, the mouse style stops changing from cursor to pointer.

**Comment by jscastro76** [comment]
This is not a but but a by design feature.
you can use the property `tb.defaultCursor` on map load event to define you favorite.

**Comment by John2397** [comment]
Sorry for the late reply. I've also tried the `tb.defaultCursor` before posting.
However, after your reply I realized I didn't use the latest `threebox` version!
