### ISSUE TITLE
About whether followPath supports carrying height to move

### ISSUE THREAD

**Issue by Dongsheng-Zhang** [jscastro76/threebox#296]
Excuse me, we are going to use followPath to animate the trajectories of the model, to our surprise, it can only move in the plane, we want to move the model at different heights
`    this._model3dInstance.followPath(
        options,
        function() {
            _this.stop()
            _this.delete()
        }
    );`

**Comment by jscastro76** [comment]
`followPath` method supports altitude, indeed there’s an example that shows exactly the [path followed by an airplane](https://github.com/jscastro76/threebox/blob/master/examples/19-fixedzoom.html)
![1EC6680F-526B-492A-A231-859506415A95](https://user-images.githubusercontent.com/38470852/141789350-d8f1937e-9db3-4437-ba2a-4cabf65af7c0.jpeg)
