### ISSUE TITLE
Error while importing threebox-plugin in script.

### ISSUE THREAD

**Issue by akshayshetty25** [jscastro76/threebox#300]
**Threebox version - 2.2.5**:

### Question
Hi All! I'm trying to use the threebox-plugin in the script using import. But the problem is its giving the error while loading the page as below
![image](https://user-images.githubusercontent.com/73101341/144975232-7942de16-6ce6-47b0-9860-e13f76daa36d.png)

I'm not able to resolve this issue, can anyone help me to find out what is causing this?
I even tried different ways like this issue in the three-js forum 
https://discourse.threejs.org/t/error-relative-references-must-start-with-either-or/13573  But nothings working.

Also, Everything works fine after that and I can even build the project without errors. But again while loading the page same error occurs.

**Comment by jscastro76** [comment]
Hi @akshayshetty25 
The error you post seems like a relative path is wrong. Without seeing your code there’s not too much I can do, please provide a minimum reproducible example in your favorite code sandbox showing the issue

**Comment by akshayshetty25** [comment]
Okay I'll try to create a example as soon as possible,
Thank you for the response.
