### ISSUE TITLE
enableSelectingObjects and enableDraggingObjects not work on ReactJS

### ISSUE THREAD

**Issue by nutthapol-jr** [jscastro76/threebox#303]
this is my code 

import { Threebox } from 'threebox-plugin'

const tb = (window.tb = new Threebox(e.target, e.target.getCanvas().getContext('webgl'), {
    realSunlight: true,
    passiveRendering: true,
    sky: false,
    enableSelectingObjects: true,
    enableDraggingObjects: true
}))

**Comment by jscastro76** [comment]
Hi @nutthapol-jr 
Thanks for sharing an issue.
Please provide a minimum reproducible example in your preferred code sandbox, otherwise there are not too many things I can do to help you

**Comment by Dildar-Khan** [comment]
Hello @jscastro76 
is it possible to do something like this with 3D-model in threebox.
https://www.bienici.com/annonce/vente/villeneuve-la-garenne/programme/1,5piece/edouard-denis-0063__62934?q=%2Frecherche%2Fachat%2Ffrance%2Fappartement%3Fcamera%3D14_2.3134037_48.9357583_0.9_0

sorry for spamming here but there is no way to contact you directly via email
