### ISSUE TITLE
Can we configure 3D model using threebox?

### ISSUE THREAD

**Issue by Dildar-Khan** [jscastro76/threebox#305]
Hello @jscastro76 
is it possible to do something like this with 3D-model in threebox.

https://www.bienici.com/annonce/vente/villeneuve-la-garenne/programme/1,5piece/edouard-denis-0063__62934?q=%2Frecherche%2Fachat%2Ffrance%2Fappartement%3Fcamera%3D14_2.3134037_48.9357583_0.9_0

**Comment by jscastro76** [comment]
I can’t see anything in that link
![6D86D476-7B7C-47E3-978E-6187F5149198](https://user-images.githubusercontent.com/38470852/147054079-a8833a87-f937-4e75-b893-21aa527db93c.png)

**Comment by Dildar-Khan** [comment]
Please open it in laptop with mobile it doesn't work well

**Comment by jscastro76** [comment]
Can’t you simply post a picture?

**Comment by Dildar-Khan** [comment]
![1](https://user-images.githubusercontent.com/26489941/147194414-8eb197d5-d9d2-4d70-893d-387cccc86ff8.jpg)
![2](https://user-images.githubusercontent.com/26489941/147194422-afdc56c1-e416-4395-9c16-7ab640e26823.jpg)
![3](https://user-images.githubusercontent.com/26489941/147194426-c0ad5a90-d693-42cb-8207-cd8d27bc4eeb.jpg)
![4](https://user-images.githubusercontent.com/26489941/147194432-ad7605f5-7b0f-4217-a7e3-af098a50db94.jpg)
![5](https://user-images.githubusercontent.com/26489941/147194441-5edc96fe-4ca9-494a-93b8-8da3b2d27aca.jpg)

**Comment by jscastro76** [comment]
If you have the 3D models and it’s real scale, of course you can. Other different thing is the weight of those models and the time they will require to load
