### ISSUE TITLE
sRGB encoding in Threebox

### ISSUE THREAD

**Issue by PSP789456** [jscastro76/threebox#309]
**Threebox version**: 2.2.5

### Question
Hello. Is this possible to use THREE.sRGBEncoding method from Three.js in Threebox?

**Comment by jscastro76** [comment]
Threebox is by default using [`THREE.sRGBEncoding`](https://github.com/jscastro76/threebox/blob/edd00653e8cea30e35931c516e97150bda86024a/src/Threebox.js#L65)
