### ISSUE TITLE
extrusion.materials null by default, but not labelled as 'required' in documentation

### ISSUE THREAD

**Issue by janhaa** [jscastro76/threebox#310]
**Describe the bug**
When trying to create extrusion e.g. like this:
```
tb.extrusion({
  coordinates: [[[]]]
});
```
following error is given:
```
materials is required
| _validate | @ | utils.js?93b5:403
| extrusion | @ | extrusion.js?4ab9:18
| extrusion | @ | Threebox.js?8949:699
```

This seems to be because in https://github.com/jscastro76/threebox/blob/edd00653e8cea30e35931c516e97150bda86024a/src/objects/objects.js#L1091 the default for materials is set to null.

Expected to have materials attribute labelled as 'required' here: https://github.com/jscastro76/threebox/blob/master/docs/Threebox.md#extrusion

All the best and thank you for the great project!

**Comment by jscastro76** [comment]
Thanks, yes it must be required in the documentation

**Comment by jscastro76** [comment]
Added a new material by default and updated the sample 18 to don't send materials on the features painted.
