### ISSUE TITLE
Suggesting removal of `this.map.remove()` in `tb.dispose`

### ISSUE THREAD

**Issue by newVincentFong** [jscastro76/threebox#311]
Great piece of work you've done right here, sir.
But, with all due respect, i don't see why **Threebox** should involve in **Mapbox** 's lifecycle.
I saw your commit and changelog in [./commit/d58daedc34ec82e1202a18a28b4370d4055de0b5](https://github.com/jscastro76/threebox/commit/d58daedc34ec82e1202a18a28b4370d4055de0b5).
I get your point.
But seperating these two may benefit in two ways:
- It's much more decoupled
- In modern web development, third-party libraries are often served in the form of **Component**
    - Developers are more likely using `mapbox-vue`, `mapbox-react` or such, writing `<Mapbox />`, other than pure `mapbox-gl.js` itself
    - Libraries above integrated map's self-destruction in their so-called `Un-mount` period
    - Which overlapped with Threebox's `this.map.remove()`
    - Which can't be unwritten because it exists in our `node_modules`
    - Causing error log just like [./issues/282](https://github.com/jscastro76/threebox/issues/282)

Thus, suggest deleting ~~this.map.remove()~~

**Comment by jscastro76** [comment]
Thanks for the suggestion but this method was explicitly created to clean everything in a single method including Three and Mapbox resources allocated, and it’s already being used in production solutions. 
My best recommendation for you would be to fork the repo and remove that line.
