### ISSUE TITLE
Are selecting functions (etc.) purposely added to Mapbox Map object?

### ISSUE THREAD

**Issue by janhaa** [jscastro76/threebox#313]
**Threebox version**: 2.2.5

### Question

I was trying to figure out how to unselect a object programmatically and found this:
https://github.com/jscastro76/threebox/blob/master/src/Threebox.js#L167

So now I can call `tb.map.unselectObject()`.

This begged me the question though, whether it was intended to add these to the MapBox map object?

I am gladly helping with any planned API improvements here.

All the best!

**Comment by jscastro76** [comment]
Yes, the intention was to elevate the selection of 3D objects from Three.js to the level of Mapbox features, getting a single selection behavior for both and identifying always a single object and feature selected that can have similar event handlers.
For several versions the object selected was in Threebox object, and the Feature selected was within Map object, which had some issues. It was easier to manipulate them under the scope of map, also including the Overed Feature/Object.
But the logic was defined for a single object/feature selected so the method to select implies unselect also any other preselected object/feature. 

A few lines below your link, you can find the logic for all the cases of selection. Probably this can be refactored in a single method for object selected allowing it to make it 100% programmatic, considering it would require a lot of functional testing to ensure nothing is broken

**Comment by janhaa** [comment]
Hi @jscastro76,

Thank you for the insights! I am actually working on some of 

> to make it 100% programmatic
I actually implemented this in my fork of your repo today :) Will come at you with some pull requests soon probably!
