### ISSUE TITLE
Render order calculation issue?

### ISSUE THREAD

**Issue by janhaa** [jscastro76/threebox#314]
**Describe the bug**
I am heavily using extrusions at the moment to dynamically generate geometry. For some reason some geometry that should be behind other geometry is rendered on-top, as seen in following clip:

https://user-images.githubusercontent.com/1587235/148129714-6866353b-57d1-4ade-b81b-76f434365ae1.mp4

To add geometry I am simply using code like this right now:
```
  const material = new THREE.MeshPhongMaterial({
    color: opts.color ?? 'white',
    transparent: false,
  });

  // create threebox extrusion
  const extrusion = this.threebox.extrusion({
    coordinates: inputGeometry.coordinates,
    geometryOptions: { depth: (opts.height ?? 1) * 0.035, bevelEnabled: false },
    materials: material,
  });
```

Any idea where this issue comes from?

**Comment by janhaa** [comment]
Nevermind, I forgot that I was doing some more stuff after creating the extrusion and before adding it to the scene, namely wrapping it into a THREE.Group along with THREE.LineSegments (as an attempt to display wireframe).

Removing that code and adding the extrusion directly solved it.

**Comment by jscastro76** [comment]
Great you found your own solution and happy Threebox is helping you to cover your needs
