### ISSUE TITLE
PostProcessing branche when addpass model refresh error

### ISSUE THREAD

**Issue by zhiqunDLUT** [jscastro76/threebox#315]
**Describe the bug**
addpass model refresh error

**Screenshots**
![image](https://user-images.githubusercontent.com/31470793/148196066-184cc5e1-c1ae-4a03-8a6b-fba26125067d.png)

just run demo，i addpass in mapbox-gl also find the problem too.
i need some help

**Comment by jscastro76** [comment]
That branch is not supported anymore, sorry, many things have changed in Mapbox and Three.js since then. There are other issues explaining all the reasons
