### ISSUE TITLE
Is it possible to add a 3D Object using 4 corner points?

### ISSUE THREAD

**Issue by John2397** [jscastro76/threebox#318]
I would like to ask if it's currently possible (or perhaps a workaround?) or if it will ever be in the future, to place a 3d object on the map by providing its 4 corner coordinates ( just like [mapbox does it](https://docs.mapbox.com/mapbox-gl-js/example/image-on-a-map/)) instead of providing its center position and rotation.

Couldn't find anything on documentation.

**Comment by jscastro76** [comment]
If a model it’s in the right scale, why do you need 4 coordinates? You only need to put the center in one corner and adjust the rotation. Also you can do that with extrusions providing four points and an altitude. 

Remember all the stuff provided in this plug-in for 3D models are not part of Mapbox but Three.js, so the same way it’s not possible in three.js by default, it’s not possible either in Threebox.

If what you want is to make a 3D model, whatever the size and rotation, and to be distorted to fulfill a set of 4 coordinates, for that you will need:
- first to load the model
- rotate it north oriented
- calculate its size in coordinates
- Calculate the size of the 4 points and find the scale factor for each axis. (I assume you will need to apply it to altitude too)
- rescale there model applying the scale factor to the model 
- Reposition the object based on 1 corner and rotate
Honestly, that’s like using a sledgehammer to crack a nut, but if that’s your need, those are the steps

**Comment by John2397** [comment]
Yes, I agree with you! Actually, the problem is that I only have the 4 coordinates. You are right, I could put the center on one corner. But I would still be missing the correct rotation. ( I want the object to be automatically adjusted/rotated at its correct position, without manual intervention).

The 3d object is a result of many 2d images, using [Open Drone Map](https://www.opendronemap.org/).

So I guess the right question should've been if it is possible to calculate the bearing (rotation) of the object knowing only the 4 coordinates, which I guess it's not, if the drone's direction is not known.

Anyway, will take a deeper look on the options of ODM. Thank you for your input!
