### ISSUE TITLE
Question about usage of unprojectFromWorld method in Threebox

### ISSUE THREAD

**Issue by PSP789456** [jscastro76/threebox#321]
**Threebox version**: 2.2.5

### Question
Hello! Some time ago I asked about Threebox models positioning (https://github.com/jscastro76/threebox/issues/308#event-5822825499). This question is related to previous one and is next: How to properly use **unprojectFromWorld** method in Threebox?
 I am trying to use vector coordinates written in my .glb file to position model on the map, but when I am trying to transform vector coordinates to LngLat coordinates with the help of **unprojectFromWorld** method I have wrong value returned every time [-0.10953688859939575, -0.004449659693231844, -14759.202515220006] (expected array of 2 numbers, latitude and longitude). Here is codepen example: https://codepen.io/psp789456/pen/yLzxdXv?editors=1000 (codepen line 79)
And the second question is: How do I retrieve mesh vector coordinates in Threebox (in Three.js I can do this by referencing to gltf scene's children, line 74 in codepen example: https://codepen.io/psp789456/pen/oNGPrLO?editors=1000 model there uses vector written to .glb file and positioned well on the map. How can I replicate this behaviour in Threebox?

**Comment by PSP789456** [comment]
I resolved the problem by using anchor: "auto" as loadObj argument. Now every .glb model I import is exactly in the place where I need.

**Comment by jscastro76** [comment]
Hi @PSP789456 
Thanks for reporting the issue and question and for taking the time to do the reproducible examples, I was taking a look to it right now as I couldn't visualize your issue before. 

Glad you found the solution quickly, and happy threebox is useful for your scenario. Yes, `anchor: auto'` will use the default anchor of the object without any modification. 

I'm also seeing your rotation must be `y: 180`
```js
		rotation: { x: 90, y: 180, z: 0 }, 
		anchor: 'auto'
```

![image](https://user-images.githubusercontent.com/38470852/148801406-9e747164-7cbd-496d-9c7f-06b23d8a2142.png)

I see lights are different in both but you can fine tune that too in threebox.

**Comment by PSP789456** [comment]
Hello again. Thank you for answering my question and supporting/updating this fork. I really enjoy using this library and it resolves many problems in my project.
You mentioned problem with lights in my Threebox scene. I would like to use baked textures and lights disabled in my project but I have some problems with adding baked textures to .glb textureless model in Threebox, which was loaded with gltf.loader (https://codepen.io/psp789456/pen/VwMEBjN?editors=1000) I did this in Three.js and it works (https://codepen.io/psp789456/pen/bGomKpZ?editors=1000) but can't find a way to make this work with Threebox.

**Comment by jscastro76** [comment]
You can add your textures under the scope of `tb.loadObj` which is equivalent to the `loader.load` event
```
tb.loadObj(options, function (model) {
   let building = model.setCoords(origin);
   // add here your textures, building is loaded
   // instead of traverse the scene you can now use `building.model` which is the child object of the scene
   tb.add(building);
})
```
I hope that helps!

**Comment by jscastro76** [comment]
Happy to hear that!
