### ISSUE TITLE
How to add CSS3D 

### ISSUE THREAD

**Issue by zhiqunDLUT** [jscastro76/threebox#322]
these is some panel put in css3D with three.js
how to add it in mapbox?
thank you

**Comment by jscastro76** [comment]
This would be more a question for StackOverflow than Threebox. You have support for CSS2D in Threebox, it's used heavily on Labels and Pop-ups. CSS3D is not included, I never tried or found the need to implement it. If you can explain your need I'd understand better what you need.

However, while ago before including in CSS2D in Threebox, I developed [an example just using CSS2D](https://github.com/mapbox/mapbox-gl-js/issues/9814) adding the feature request for Mapbox. As CSS3D implementation pattern is quite to CSS2D, you can surely follow [this example to create a CSS3D instead](https://jsfiddle.net/jscastro76/h3obxpju/9/). You have to paste your token in the fiddle first line.
