### ISSUE TITLE
Azure Maps sample doesn't work if you change map style

### ISSUE THREAD

**Issue by rbrundritt** [jscastro76/threebox#323]
If you load the Azure Maps sample, then change the map style, the 3D model disappears and doesn't come back.

**Comment by jscastro76** [comment]
Humm... let me check it out!!!

**Comment by jscastro76** [comment]
Interesting, it worked twice with the default style to terra and road, but they disappear on Greyscale...

I'm seeing that the console returns this:
```console
atlas.js:505 Unable to perform style diff: Unimplemented: setSprite..  Rebuilding the style from scratch.
```

It seems the control performs a full reload so the custom layer is not reloaded becuse the event is  `map.events.add("load",...`  ... so changing it to 
```js
map.events.add("style.load"... 
```
