### ISSUE TITLE
How to change renderorder with mapbox

### ISSUE THREAD

**Issue by Philip2809** [jscastro76/threebox#329]
**Threebox version**: ^2.2.5

### Question

Is there any way to set different render orders for the items in threebox and mapbox. When I add a layer for threebox it does not show up in the layers list and therefor can't order them that way, I can't neither set a three renderOrder as that only applies for the three js objects. Basically I have two three js items, and a geojson layer in mapbox geojson layer (building). I basically need to draw one threebox object (floormap) then the building (mapbox geojson) and lastly the  markers, green objects. At the current time it looks like this:
![image](https://user-images.githubusercontent.com/51290462/152822885-72b5345b-e1ea-4c80-a699-11ac0e2b0192.png)

And when I change the drawing for the floormaps, so they are correct the green markers go behind the building.
![image](https://user-images.githubusercontent.com/51290462/152823401-4b3c1440-a7ac-40b5-b491-fccfe43d2020.png)

Any ideas how to fix this? My idea is to move the building geojson to treeboxes building instead and use renderOrder, if that even would work.

**Comment by jscastro76** [comment]
Then you'll need to create 3 layers (3D, fill-extrusion and 3D) and define the order they will be rendered. 
you have an example on how to render the 3D layer first on the [example number 7](https://github.com/jscastro76/threebox/blob/master/examples/07-alignmentTest.html)

```js
map.addLayer({
	id: 'custom_layer',
	type: 'custom',
	renderingMode: '3d',
	onAdd: function (map, mbxContext) {
		},
	render: function (gl, matrix) {
		}
	}, 'room-extrusion'); //if you add the name of the fill-extrusion layer it will render before
```

**Comment by Philip2809** [comment]
Hi jscastro!

I tried this; but the layer did not show up in my `map.getStyle().layers` array, is this normal? Does it now show the "custom" type layers?

**Comment by jscastro76** [comment]
Yes, it's normal, custom Layers are not shown at `map.getStyle().layers`, I don't know the reason.
Regarding your second question, if you read the [documentation for the `tb.add`](https://github.com/jscastro76/threebox/blob/master/docs/Threebox.md#add), you'll see the method accepts the layer to add the object as a param;
```js
tb.add(obj [, layerId, sourceId])
```
If you take a look to the examples, [example 16 shows you how to create multiple layers ](https://github.com/jscastro76/threebox/blob/master/examples/16-multilayer.html) and even manage different zoom levels for each one separately.

PS.- **Never use `tb.world.add` directly**, as you will lose control over the tooltips, labels of the object and the layer where the object is. Check what the [method `tb.add`](https://github.com/jscastro76/threebox/blob/37e774ab700163d09ac798e8663731e95632d68e/src/Threebox.js#L916) is doing to understand all the things this method does.
Hope this helps!
Jesus
