### ISSUE TITLE
Problems with Object Rotation

### ISSUE THREAD

**Issue by Pexeus** [jscastro76/threebox#334]
I am trying to create a 3D Visualization of an RC airplane in Threebox. The RC plane sends live telemetry, including:
- GPS Coordinates
- Gyro sensor data, showing the pitch, roll and heading of the plane.

I have now loaded a Model of an airplane in Threebox, no problems with that. 
My problem comes down to the rotation of the plane. I want the plane object to represent the current orientation of the RC plane. Since I have the live telemetry from the flight controller, this should be possible.

In the Documentation, I have found this method, which seemed like exactly what i needed:
` plane.setRotation({x: roll, y: pitch, z: yaw/heading})`

And it basically works. I can rotate the Plane around its axes. But things get messed up when I combine the rotations.

For example: When I just update the roll axis, the Object behaves just like I want it to. However, when i change the heading of the plane by 90 degrees, the roll axis suddenly becomes the pitch axis. It seems to me, that the axes of the Plane object don't rotate with  the plane itself.

I've prepared a recreation of the issue on [jsfiddle](https://jsfiddle.net/ny3g0hLj/2/). You can change the heading of the plane using the slider in the bottom right.

I've been stuck on this for days, would be super happy for any help!

**Comment by jscastro76** [comment]
The problem with your code is that setRotation is applied to the object in it's current state, and in Three.js that's AABB (Axes Aligned Bounding Box). If you what to use your use our yaw/heading function to rotate the z axis while you keep the constant movement in an AABB over the x axis for rolling, then you have to use

```js
 plane.rotateOnAxis( new THREE.Vector3(1, 0, 0), Math.PI * x / 360);
```

I have [updated your fiddle](https://jsfiddle.net/jscastro76/k6zuna9b/1/)... but watch out, `rotateOnAxis` is a function sets the value starting from the previous value of the object (so it's incremental) as opposed to `setRotation` that sets the value directly without considering any previous value, so your constant movement function now should change. 

Anyway... it rolls now properly
![image](https://user-images.githubusercontent.com/38470852/158580919-a4aa260e-2007-4587-ad28-0d7e4e8c8c96.png)
