### ISSUE TITLE
how can i use it in R3F

### ISSUE THREAD

**Issue by moshuying** [jscastro76/threebox#337]
how do i use it in R3F?

**Comment by jscastro76** [comment]
I don't know... what is R3F?

**Comment by moshuying** [comment]
> I don't know... what is R3F?

this~ https://github.com/pmndrs/react-three-fiber

**Comment by moshuying** [comment]
This framework makes the code very readable and very easy to use. I've seen some authors use it to make great plugins, like this one https://lgltracer.com/

**Comment by jscastro76** [comment]
Hi @moshuying 
More clarity in your questions would be really appreciated if you expect an answer, this is not a Helpdesk or a Support Service.
Integrating Threebox in other plugins or frameworks is not on the scope of this open source project.

If you look in closed issues you'll find people who [integrated Threebox in react](https://github.com/jscastro76/threebox/issues/262), or [this](https://github.com/jscastro76/threebox/issues/286), or [this](https://github.com/jscastro76/threebox/issues/311), or [this](https://github.com/jscastro76/threebox/issues/178), or [this](https://github.com/jscastro76/threebox/issues/161), or [this](https://github.com/jscastro76/threebox/issues/116)

**Comment by moshuying** [comment]
> Hi @moshuying More clarity in your questions would be really appreciated if you expect an answer, this is not a Helpdesk or a Support Service. Integrating Threebox in other plugins or frameworks is not on the scope of this open source project.
> 
> If you look in closed issues you'll find people who [integrated Threebox in react](https://github.com/jscastro76/threebox/issues/262), or [this](https://github.com/jscastro76/threebox/issues/286), or [this](https://github.com/jscastro76/threebox/issues/311), or [this](https://github.com/jscastro76/threebox/issues/178), or [this](https://github.com/jscastro76/threebox/issues/161), or [this](https://github.com/jscastro76/threebox/issues/116)

tks~
