### ISSUE TITLE
Custom shader

### ISSUE THREAD

**Issue by yan-map** [jscastro76/threebox#344]
Hello!
Is there any way to implement custom three.js shader to mapbox geometry, such as SAO to mapbox 3d buildings?

**Comment by jscastro76** [comment]
You have an example of a shader using Mapbox buildings in [BuildingShadows](https://github.com/jscastro76/threebox/blob/master/src/objects/effects/BuildingShadows.js) and a [example of how to use it](https://github.com/jscastro76/threebox/tree/master/examples#14-buildingshadowhtml)
