### ISSUE TITLE
What's the unit of the raycaster.intersectObjects point by click event? 

### ISSUE THREAD

**Issue by hong4k** [jscastro76/threebox#345]
when click the model,the workflow:

1. queryRenderedFeatures(e.point)
      |
2. get intersects (the below pic)
      |
3. selectedObject.selected = true

What is the unit of the intersect object point(**2)** ? meters?
we want to convert intersect point xy to lnglat, This lnglat  is different from the lnglat obtained by mapbox click event.

<img width="995" alt="image" src="https://user-images.githubusercontent.com/21072150/162160477-f059d8ac-263e-4048-ac25-0969f5f7d164.png">

**Comment by jscastro76** [comment]
Based on [threejs documentation](https://threejs.org/docs/index.html?q=ray#api/en/core/Raycaster) it’s the point of intersection in world coordinates
