### ISSUE TITLE
Objects penetrate each other when terrain is false

### ISSUE THREAD

**Issue by hong4k** [jscastro76/threebox#346]
The blue polygon is mapbox layer.
Threebox version:2.2.4

> terrain is false
<img width="584" alt="image" src="https://user-images.githubusercontent.com/21072150/162362406-95374631-a709-4c02-b465-41ca1cfbb735.png">

> terrain  is true

<img width="622" alt="image" src="https://user-images.githubusercontent.com/21072150/162362653-7828172b-e3b2-4a83-95ec-c36290974743.png">

**Comment by jscastro76** [comment]
With no code I cant help too much... what's the creation order you're doing?

**Comment by hong4k** [comment]
OK, I'm doing the exclusion test and decoupling the demo

**Comment by jscastro76** [comment]
You’re probably creating first the 3D later than the Fill layer.

**Comment by hong4k** [comment]
Thanks a lot, that's the reason, the order of things. solved! !
