### ISSUE TITLE
THREE.PlaneHelper runs abnormally and rotates with the camera angle, and the clippingPlanes parameter in Material is also abnormal.

### ISSUE THREAD

**Issue by yusongyi** [jscastro76/threebox#351]
**Describe the bug**
1.The normal vectors set by Plane are not the same, but the PlaneHelper displays overlap.
2.After setting clippingPlanes for the object, it seems that the object is the center origin, not the axis center origin. And the clip is triggered when the map is dragged.

**To Reproduce**
Please zoom in on the map and you can probably see the PlaneHelper in Africa.
https://yii45b.csb.app/

**Relevant Code or Code Sandbox**
https://codesandbox.io/s/vue-threebox-sample-forked-rlo8el?file=/src/components/ThreeboxExample.vue:2621-2635

**Screenshots**
![image](https://user-images.githubusercontent.com/36191243/167596765-47f7c746-3d2f-4419-bc35-873874355b7a.png)

- [Version [e.g. 2.1.7]
v.2.2.7

**Comment by jscastro76** [comment]
Z is altitude in mapbox (x,y are lat/long). Y is altitude in three.js, and Z in depth axis.
