### ISSUE TITLE
fixedZoom Doesnt work for many objects in one layer

### ISSUE THREAD

**Issue by tovaz** [jscastro76/threebox#353]
Im working adding many objects in one layer, all have fixedZoom with 18 but only one is scaling fine, others are always small, arent scaling;
I have used your example 19-fixedZoom.html just added a loop to add 5 objects; but it doesnt work as spected.
<img width="1051" alt="Captura de Pantalla 2022-05-19 a las 23 14 00" src="https://user-images.githubusercontent.com/11469828/169405675-28dcc135-9846-4dab-9492-94fc15de43fd.png">

I just modified this lines
<img width="1283" alt="Captura de Pantalla 2022-05-19 a las 23 15 52" src="https://user-images.githubusercontent.com/11469828/169405925-12133b53-e2fe-4290-822a-52163f267173.png">

Do I need to do something else to make it works, or is it the right behavior ?
I think using many layers it could works, But I didnt try that; 

I have created this jsfiddle but I couldnt load the model on the map I dont know why.
https://jsfiddle.net/tovaz/sm9f6h0c/52/

**Comment by jscastro76** [comment]
I have deployments with hundreds of fixed zoom objects, whatever the issue you’re facing is not a bug in threebox.

**Comment by tovaz** [comment]
> I have deployments with hundreds of fixed zoom objects, whatever the issue you’re facing is not a bug in threebox.

OK, let me check and try...
