### ISSUE TITLE
Tooltips using altitude & Mouse over/out, Selected, Drag&Drop, Drag&Rotate, Wireframe Examples 

### ISSUE THREAD

**Issue by Takieddinex** [jscastro76/threebox#355]
Hey ! 
I would like to test and use the two examples shown in the home page. Thank you for sharing the code for the two examples :
* Tooltips using altitude
* Mouse over/out, Selected, Drag&Drop, Drag&Rotate, Wireframe Examples 
Thank you

**Comment by jscastro76** [comment]
They are both in examples folder
[Tooltips](https://github.com/jscastro76/threebox/blob/master/examples/08-3dbuildings.html)
[Interactions](https://github.com/jscastro76/threebox/blob/master/examples/11-animation.html)

**Comment by piedmontlong** [comment]
Hey Jesus,

If I want to hover/select the threebox line, tube instead of extruded features or objects and add tooltips, do you have examples or code snippets? 

Thank you!
