### ISSUE TITLE
Is it possible to disable the tooltip when dragging/rotating objects?

### ISSUE THREAD

**Issue by axekan** [jscastro76/threebox#356]
**Threebox version**: 2.2.6

### Question
I'm using Threebox to load in interactive 3d models of buildings to my map and allowing the user to drag and rotate the objects. I was trying to figure out a way to disable the label showing coordinates and rotation when performing these actions as they don't really serve a purpose for the end-user. 
I could not find anything in the documentation about turning this off, and looking through they sourcecode it seems to be pretty deeply rooted in the `onMouseMove` event through `object.addHelp()`.

[Short video showcasing what I'm talking about](https://i.gyazo.com/4b54e2c09b50392c3b369f36c0616c78.mp4).

Is there something I'm missing in regards to configuring this tooltip function? I apologize if this has been answered before, but I was unable to find anything.

**Comment by jscastro76** [comment]
Hi @axekan
In my case, in all my projects that's one of the features that is better valued, because it helps the designers to do fine grain adjustments. Having said so, you're right, there's no option to turn them off, and it should as it happens with other tooltips.
Converting this question into a new feature.
I'll post here when it's ready.

**Comment by jscastro76** [comment]
Now this help tooltips are hidden always. If anyone wants to make them visible, they can use `enableHelpTooltips: true` as a Threebox param

**Comment by jscastro76** [comment]
That's not help tooltip, that's the bounding box. If you want to deactivate it, you have to use `bbox: false` in each object creation params

**Comment by liuchang567** [comment]
> That's not help tooltip, that's the bounding box. If you want to deactivate it, you have to use `bbox: false` in each object creation params. [You already have an example of this here](https://github.com/jscastro76/threebox/blob/9081d4f311621e972cdcb03ee443c14d828b7b4a/examples/09-raycaster.html#L97)

yes my fault, thank you and look forward to the project getting better and better
