### ISSUE TITLE
Clean up after use 

### ISSUE THREAD

**Issue by ShaneTex** [jscastro76/threebox#36]
I have in my process a way to load new models on demand, but there will be a set for each location via xml, is there a way to clean up or dispose of all models, prior to loading new ones?  I did see a way to completed dispose of tb, but only if you you navigating away from the site, is there a way to keep it clean as you go, and only clean up sets of models.

**Comment by jscastro76** [comment]
You can remove now the models one by one using `tb.remove`. I’m gonna try to solve this one and #35 at the same time with the method `tb.clear`, I’ve been testing with different loop methods and I will do a `while (tb.world.children.length > 0)` and in the loop do a `tb.remove(model)`. 
I tried with for, forEach and traverse and all of them are not suitable to remove items in the collection that is being looped, so while would be my best bet

**Comment by ShaneTex** [comment]
@jscastro76 That sounds great, thanks

**Comment by ShaneTex** [comment]
@jscastro76 Also, is there a way to turn off the wireframe around a model, but still be able to select, and highlight, etc.

**Comment by jscastro76** [comment]
> @jscastro76 Also, is there a way to turn off the wireframe around a model, but still be able to select, and highlight, etc.

you can set `obj.boundingBox` and `obj.boundingBoxShadow` to null once the object is loaded. I have a pending issue open #3 to make the color of these bounding boxes configurable

**Comment by ShaneTex** [comment]
Gotcha, sould would I use this to remove or clean all:
while (tb.world.children.length > 0) {
                tb.remove(tb.world.children[0]);
            }

**Comment by ShaneTex** [comment]
On the bounding box, thanks that is great

**Comment by jscastro76** [comment]
> Gotcha, sould would I use this to remove or clean all:
> while (tb.world.children.length > 0) {
> tb.remove(tb.world.children[0]);
> }

I'm working quickly to deliver v.2.0.5 with these changes done, so you will only need to call `tb.setStyle` instead of `map.setStyle`.

> On the bounding box, thanks that is great

I have no time to add issue #3 for this release, so you should set those to null in every object loaded, so I would do something like this...

```js
tb.loadObj(options, function (model) {
	model.setCoords(originCoords);
	model.boundingBox = null; //this removes the yellow/green box
	model.boundingBoxShadow = null; //this removes the black floor projection box
	tb.add(model);
})
```

**Comment by ShaneTex** [comment]
Awesome, will do.

**Comment by ShaneTex** [comment]
that works perfectly
