### ISSUE TITLE
Loading many GLTF models with ThreeBox plugin  

### ISSUE THREAD

**Issue by Takieddinex** [jscastro76/threebox#361]
Hello,

I'm passionate about this great plugin but I'm having a problem loading multiple 3D models. I used this code https://github.com/jscastro76/threebox/blob/master/examples/11-animation.html 
but my modest development skills prevent me to find the solution 
could you please guide me ! 

Thank you

**Comment by jscastro76** [comment]
For loading multiple instances of the same model I recommend you [to check this example out](https://github.com/jscastro76/threebox/blob/master/examples/15-performance.html)

**Comment by jscastro76** [comment]
I don’t understand what’s the issue you’re facing. If you want to load different objects based on different options, I’d create an array with all the properties needed and then I’ll create a loop over them to create the instances similar to how it’s done in the sample I shared
