### ISSUE TITLE
High idle CPU usage caused by simply initializing Threebox.

### ISSUE THREAD

**Issue by axekan** [jscastro76/threebox#362]
**Describe the bug**
I am having some issues with performance whilst using Threebox in my project. After Threebox has been attached to window, the idle CPU usage of my browser does go down fully. I'm currently using chrome but have experienced the same behavior on Brave, Edge and Safari. Removing the window.tb declaration resolves this issue completely, allowing the browser's CPU usage to go down to 0% - 0.5%, compared to 10%-20% when having Threebox active.
CPU usage percentages are obviously different on whatever PC you are using, but I have experienced an unually high idle usage from Threebox on at least 3 different computers (running 3 different OS's even).   

**Steps to reproduce**
1. Initialize a Mapbox map and add threebox. 
2. Observe how your CPU usage and notice it doesn't go down fully when switching to another browser tab or going to another window. 
3. Comment out or remove the loading of threebox and check if CPU usage goes down when switching tabs or window.

**Expected behavior**
Some performance overhead is expected since we are adding a 3D library to mapbox, but the idle usage shouldn't be this high since we aren't even adding any models or 3D objects. The different lighting options doesn't seem to affect this either.  

[**Codepen showing the behavior**](https://codepen.io/axekan/pen/ExEKoMR)

In this codepen, my CPU usage when idle or in another window stays at 9%-12%. Commenting out Threebox as explained above lowers it to just above 0%.

A workaround in my instance would probably be to dispose of tb when not using a 3D model, but I'm hoping there is some other way around this.

**Comment by jscastro76** [comment]
That’s why `tb.dispose` was implemented. There are several issues closed explaining why three and also mapbox keep memory in use that is not de-allocated by the browser
Indeed the original project didn’t dispose any single object when removing so there was an important memory leak through progressive use

**Comment by axekan** [comment]
I've done some further investigating and weirdly the CPU usage goes down as soon as I add my 3D model through a button click. I add my model using this this:
```
document.addEventListener('addhouse', async (e) => {
  if (this.getLayoutProperty('3d-model', 'visibility') === 'visible') {
      $(`#${e.detail.button}`).html('Add 3D model');
      await tb.clear();
      this.house_visible = false;
      this.setLayoutProperty('3d-model', 'visibility', 'none');
  } else {
      $(`#${e.detail.button}`).html('Remove 3D model');
      await sup.addModel('woodhouse', 3);
      this.house_visible = true;
      this.setLayoutProperty('3d-model', 'visibility', 'visible');
  }
  });
```
and upon triggering this event for the first time, it seems to resolve itself.

I was thinking about changing dispose so that the map remains when running it, so that I could use it on just threebox. But it seems that may not be necessary.
