### ISSUE TITLE
How to load the GLB model stored in IndexDB, or the local GLB model file, Threebox load the model only in the URL way?

### ISSUE THREAD

**Issue by yinminhe** [jscastro76/threebox#368]
How to load the GLB model stored in IndexDB, or the local GLB model file, Threebox load the model only in the URL way?

**Comment by jscastro76** [comment]
This plug-in is using Three.js loading methods, so your question is more related to three.js than Threebox 
If you’re able to load a GLB model on three.js stored on an IndexDB, that would be the starting point but it’s not definitely a relevant or demanded use case so far
