### ISSUE TITLE
Anchor options

### ISSUE THREAD

**Issue by ShaneTex** [jscastro76/threebox#37]
Is there a way to use the models built in origin for attaching to custom layers. All of our assets we have already assigned the origin to left front of a building of the 3D model in blender before we export, we can get the center of volume, but that doesn't always match perfectly, then we get the lat/lon coordinates. Since we only have center, left, right we basically have to position or tweak the position on many objects again.

Can we use the internal origin for anchoring?

**Comment by jscastro76** [comment]
I could implement quickly an option `none` for the anchor options... that will basically do nothing to calculate the position of the 3D model, so it will be positioned as is

**Comment by ShaneTex** [comment]
That would be fantastic.

**Comment by jscastro76** [comment]
> That would be fantastic.

consider it done... I'm just updating documentation and checking tests. if everything works well and I don't find any issue, I will push the commit tomorrow for v.2.0.5 release

**Comment by ShaneTex** [comment]
Thanks so much

**Comment by jscastro76** [comment]
No, thank you for providing feedback and needs.
