### ISSUE TITLE
Support for MapLibre V2?

### ISSUE THREAD

**Issue by John2397** [jscastro76/threebox#375]
Recently, I [migrated](https://github.com/maplibre/maplibre-gl-js#compatibility-branch) from `Mapbox V1` to `Maplibre V1` as Mapbox became closed source. Since `Maplibre V1` is completely backwards compatible with `Mapbox V1`, the only thing I had to change was the [CDN links](https://github.com/maplibre/maplibre-gl-js#cdn-links) and replace everywhere the word `mapboxgl` with `maplibregl`.To my surprise, threebox was working seamlessly as well. 

However, when I tried to update `Maplibre V1` to `Maplibre V2`, I got the following errors coming from `threebox`:
![Screenshot from 2022-11-10 11-37-39](https://user-images.githubusercontent.com/68916468/201055392-38f0542d-9ff9-4d86-ab8b-38e743599545.png) which indicates incompatibility between them (I suppose?).

My question is, are there any plans on the table to make `threebox` compatible with `Maplibre V2`?

**Comment by tovaz** [comment]
Hello; I got same issue;
Decrease Threebox version number to V 2.2.1 it works;
But the objects are not updating while changing color or hidden propertie;

<img width="1182" alt="Captura de pantalla 2022-11-10 a las 12 09 08" src="https://user-images.githubusercontent.com/11469828/201075892-a0daa682-1185-46ed-96e0-869be700a6ca.png">

**Comment by MrDevAjay** [comment]
I also have this same issue. 3D icons are not showing.  can not read propertied of undefined 'position' error is showing

**Comment by jscastro76** [comment]
Thanks for reaching out @John2397, @tovaz, @MrDevAjay!
This plugin was not implemented to be compatible with MapLibre but Mapbox and AzureMaps on the versions supported and described by the [README.md](https://github.com/jscastro76/threebox/blob/000aa02680e5e161f4b72e74c0099ae065b22768/README.md), I'm indeed surprised it still worked on another maps' engine.
But as this repo is MIT license, you have rights to fork the project to create your own implementation.

**Comment by douglasg14b** [comment]
@jscastro76 You should really reconsider this. Maplibre **IS** mapbox before they went proprietary, it's the community fork of it. It's not a different engine

>  But as this repo is MIT license, you have rights to fork the project to create your own implementation.

Community fragmentation makes these issues worse, not better :(

Just found this project and was super excited, but since it's proprietary mapbox only, but doesn't support the community mapbox fork, it's kind of a bummer.

How much work would you think would be necessary here?

**Comment by jscastro76** [comment]
Thanks @douglasg14b for your feedback, but

**Comment by jscastro76** [comment]
Thanks @douglasg14b for your feedback!
This code is already in production in different projects using Mapbox and Azure Maps, which are the platforms it was designed and implemented for. It's been downloaded 160K times as NPM module, there's +100 forks and reused by hundreds of other projects. As said, this is an open source project under MIT license, which gives you a lot of benefits and rights completely for free, but this is not a Support desktop with an SLA.

**Comment by nicky132** [comment]
![image](https://user-images.githubusercontent.com/34881461/211584122-2dc6bb2d-650b-43ed-aa46-f63ad046f82a.png)
Hope someone do anything about threebox to support maplibre2

**Comment by hkb1990** [comment]
add
```
Object.defineProperty(map, 'version', {
  get: function () {
    return 1.0;
  }
});
```
before
 ```  
window.tb = new Threebox(
  map,
  map.getCanvas().getContext('webgl'), //get the context from the map canvas
  { defaultLights: true }
 );
```
then you can use threebox in Maplibre.
`NOTE: map is new maplibregl.Map`
