### ISSUE TITLE
Instancedmesh Support

### ISSUE THREAD

**Issue by rondoor124** [jscastro76/threebox#379]
**Is your feature request related to a problem? Please describe.**
Can we use three.Instancedmesh?

**Comment by jscastro76** [comment]
Hi @rondoor124!
Never tried, but as long as `new Object3D` accepts [a mesh as a param](https://github.com/jscastro76/threebox/blob/master/docs/Threebox.md#object3d) and InstancedMesh inherits form Mesh, it probably works. I'd suggest you to use [raycaster example ](https://github.com/jscastro76/threebox/blob/master/examples/09-raycaster.html) and where a geometry is created, try with your InstancedMesh instead
```js
                    //// initialize geometry and material of our cube object
                    var geometry = new THREE.BoxGeometry(30, 60, 120);

                    //[jscastro] we add a cube with no bbox and despite is raycasted
                    let cube = new THREE.Mesh(geometry, redMaterial);
                    cube = tb.Object3D({ obj: cube, units: 'meters', bbox: false})
                        .setCoords(origin1);
					cube.addTooltip("This object is selectable but without bounding box", true);
                    tb.add(cube); 
```
