### ISSUE TITLE
Add custom properties

### ISSUE THREAD

**Issue by ShaneTex** [jscastro76/threebox#38]
@jscastro76 Is there a way to load a custom url, and dataType to the model, I sort of have this working:
var options = {
                            obj: '../models/' + folder + '/' + filename,
                            type: type,
                            scale: scale,
                            units: 'meters',
                            rotation: { x: rotationx, y: rotationy, z: rotationz }, //default rotation
                            anchor: 'center'
                        }

                        tb.loadObj(options, function (model) {
                            model.setCoords(modelLocation);
                            model.boundingBox = null; //this removes the yellow/green box
                            model.boundingBoxShadow = null; //this removes the black floor projection box
                            model.addTooltip(tooltip, false);
                            model.addEventListener('SelectedChange', onSelectedFeatureChange, false);

                            if (hasLink) {
                                console.log('Hello, linkUrl!', linkUrl);
                                model.dataType = "Link";
                                model.url = linkUrl;
                            }

                            if (hasAnimation) {
                                model.playDefault(options = { duration: 100000 });
                                console.log('Hello, hasAnimation!', hasAnimation);
                            }

                            model.dataType = "Link";
                            model.url = linkUrl;
                            tb.add(model);
                        })

But when the loadObj runs, the link URL is always blank, I am sure it is becuase this run async, but I am just loading via an xml, and looping through each xml node to build the objects.  But, I can't get the animation to start for the object, unless I hard-code it, I can't do or load the data at run time.  Is there a easy way to do this, to add to options, or pass it down when load is completed.

**Comment by jscastro76** [comment]
You can introduce custom attributes in the options object. Any attribute you pass in the options object will be in `model.userData`, is copied there.

**Comment by ShaneTex** [comment]
Perfect, I was adding it directly, but it wasn't looking in userData.

Thanks again.

**Comment by ShaneTex** [comment]
thanks again
