### ISSUE TITLE
How to obtain the world coordinates of intersections？

### ISSUE THREAD

**Issue by younggis** [jscastro76/threebox#384]
queryRenderedFeatures returns the screen coordinates of the intersection, but how to convert them to world coordinates?

**Comment by jscastro76** [comment]
Check the documentation for [`utils.projectToWorld`](https://github.com/jscastro76/threebox/blob/417220468b2b099396f5d8591fa5ab9632c7d078/src/utils/utils.js#L98)

**Comment by younggis** [comment]
Thank you. The method you gave is to turn WGS84 into the world coordinates of three. Now I want to turn the intersection into the world coordinates, like the following code.
`
this.mapgl.on('click', (evt) => {
  let intersects = tb.queryRenderedFeatures(evt.point)
  if (intersects.length) {
    let feature = intersects[0]['object'];
    let worldcoordinate = tb.unprojectFromWorld(intersects[0]['point']);
  }
}）
`
I need to save the geographic coordinates corresponding to this intersection.

**Comment by younggis** [comment]
@jscastro76 Please take a look
