### ISSUE TITLE
vue.runtime.esm.js?2b0e:4605 [Vue warn]: Error in mounted hook (Promise/async): "TypeError: threebox_plugin_dist_threebox__WEBPACK_IMPORTED_MODULE_6__.Threebox is not a constructor"

### ISSUE THREAD

**Issue by chengyinl** [jscastro76/threebox#389]
import { Threebox } from 'threebox-plugin/dist/threebox'
console.log('threebox', new Threebox())

**Comment by jscastro76** [comment]
Check [this example](https://codesandbox.io/s/vue-threebox-sample-8k7mz)
