### ISSUE TITLE
A couple questions

### ISSUE THREAD

**Issue by ShaneTex** [jscastro76/threebox#39]
@jscastro76  I have a couple Questions:  

1. How do I delete specific models that I have loaded, do I have to loop through all tb.world.children and look for a name, for one to remove, or is there a way to remove via name, or Id.

2. Can I group by id, and have some objects that are meant to be animated, and not, and then remove or clean via different id's.  For example, here in addlayer, do all threebox objects need to be added to this id, or is there a smarter way.
map.addLayer({
				id: 'custom_layer',
				type: 'custom',
				renderingMode: '3d'

**Comment by jscastro76** [comment]
Hi @ShaneTex,
1. You can delete any object through [`tb.remove`](https://github.com/jscastro76/threebox/blob/master/docs/Threebox.md#remove) with the 3D object as param.

2. Of course you can create multiple layers and group in each one of them different 3D objects, that´s the standard approach for multi-floor scenarios.

**Comment by ShaneTex** [comment]
Got it so the id: can be anything, it doesn't have to be 'custom_layer'?

**Comment by jscastro76** [comment]
> Got it so the id: can be anything, it doesn't have to be 'custom_layer'?

Of course, the id is a string value [check out mapbox documentation for `map.addLayer`](https://docs.mapbox.com/mapbox-gl-js/api/map/#map#addlayer) 
For instance, I have an example with a building of N layers and each one of them is called 'floor_0', 'floor_1', 'floor_3'... dynamically base on what I read from a GeoJson file.

**Comment by ShaneTex** [comment]
Gotcha, perfect.   So you remove them the same way, so it would be tb.remove('floor_0'), etc.

**Comment by jscastro76** [comment]
> Gotcha, perfect. So you remove them the same way, so it would be tb.remove('floor_0'), etc.

You are mixing things... 
If you want to remove a 3D object, then you must use [`tb.remove`](https://github.com/jscastro76/threebox/blob/master/docs/Threebox.md#remove) 
If you want to remove a layer, then you have to use [`map.removeLayer('floor_0')`](https://docs.mapbox.com/mapbox-gl-js/api/map/#map#removelayer), but the layer won´t remove it´s 3D objects.

What I would recommend to you is to add an attribute with the layerId to each 3D object as part of their init options, then you´ll be able to loop through all them. 

I will consider to create methods to override `map.addLayer` and `map.removeLayer` to wrap up this functionality.

**Comment by ShaneTex** [comment]
@jscastro76 Gotcha, that makes better sense now.  Thanks for the help.
