### ISSUE TITLE
followPath and clear

### ISSUE THREAD

**Issue by Criska9527** [jscastro76/threebox#395]
When I call the method tb.clear('layeris', true), the followPath process for the model being executed stops

**Comment by jscastro76** [comment]
That's because you're basically disposing all the resources in that layer. It's not a bug

**Comment by Criska9527** [comment]
Thank you for your patience, but according to the design of the system layer concept, my model is loaded in layer A, but when I use clear to clear layer B, the resources in layer A should not be released

**Comment by Criska9527** [comment]
By querying the source code of the clear method, I found that as long as my clear selects dispose, then objectsCache will dispose all object objects, because this will cause my object's animation to terminate, I don't think this is reasonable, because my clear layername and the layername added to the model are not the same @jscastro76
