### ISSUE TITLE
How manually cancel the selection effect of model?

### ISSUE THREAD

**Issue by leungMr** [jscastro76/threebox#398]
when a model is selected, How manually cancel the selection effect?
If directly set the parameters `e.target.selected = false`, although the visual selection effect (bbox+tooltip) has been removed, the internal model selection status is still present, because the next click cannot trigger the selection event

**Comment by leungMr** [comment]
do you know how to solve the problem I raised? @jscastro76

**Comment by jscastro76** [comment]
If what you want is to remove the bounding box and tooltips, but keeping the selection event, you can add the attributes `bbox: false` and `tooltip: false`, if what you want is to completely hide a concrete object from being raycasted, you can use the attribute `raycasted: false`

Please, read the the [documentation](https://github.com/jscastro76/threebox/blob/master/docs/Threebox.md#object3d)

**Comment by leungMr** [comment]
Sorry, I may not have described it clearly! 
my question is, when a model is clicked and selected, how to remove its selected state, except by clicking it again？

**Comment by jscastro76** [comment]
`tb.map.unselectObject();` should solve your issues but this could conflict when you have both features and objects selectable.
