### ISSUE TITLE
Indoor

### ISSUE THREAD

**Issue by ShaneTex** [jscastro76/threebox#40]
@jscastro76 Another quick question, if I want to do indoor or floors, or something like that would I just do three.js, and not threebox, since those will most likely be higher scale that mapbox's zoom levels or higher that zoom 22.  See example:http://maps.septrio.com/mckinneyevents.html#20.93/33.1939133/-96.6129444/132/60

I basically want to be able to step into the building, see different floors, and add furniture, etc inside.

**Comment by jscastro76** [comment]
This is a Mapbox issue, nothing to do with Threebox. Honestly I do not understand their limitation on zoom level.
In my case, I have modified Mapbox latest version to increase the zoom up to 26, which is more than enough to reach centimeters precision and indoor camera position. 
It´s a bit tricky (because of their hardcoded implementation) but also it´s quite easy, you just only to look for maxZoom (there are many occurrences) and replace its value by 26.
This is one of my buildings in one of my tools
![zoom26](https://user-images.githubusercontent.com/38470852/91956290-c2ad2280-ed04-11ea-8d32-027a5ae3d624.gif)

**Comment by ShaneTex** [comment]
@jscastro76 Gotcha, so did you just download their javascript implementation, and to a find and replace then?

**Comment by jscastro76** [comment]
> @jscastro76 Gotcha, so did you just download their javascript implementation, and to a find and replace then?

You can fork or clone the [full mapbox-gl-js project](https://github.com/mapbox/mapbox-gl-js) and find the occurrences in the all the files (there are a few, believe me) and then generate you own build, or just do a find&replace carefully over the [final minimized mapbox-gl-js file](https://api.mapbox.com/mapbox-gl-js/v1.12.0/mapbox-gl.js).

**Comment by ShaneTex** [comment]
perfect, thanks

**Comment by ShaneTex** [comment]
Is there a way to be inside a 3d Model, it seems there is no way to navigate inside a model that represents a building.

**Comment by jscastro76** [comment]
> Is there a way to be inside a 3d Model, it seems there is no way to navigate inside a model that represents a building.

Of course you can, it all depends on the size of the model and the camera position. 
For instance, the electric kiosk from a power substation you can see in my video above, is a 3D model in real size over the map, but to reach that zoom level, you need to modify first the maxZoom in mapbox

**Comment by ShaneTex** [comment]
@jscastro76 gotcha, I will try that.

**Comment by ShaneTex** [comment]
@jscastro76 If I change the maxZoom, is there then any way to block or specify Occlusion for the building, so that I can control where or what part of the building the user can enter?

**Comment by jscastro76** [comment]
> @jscastro76 If I change the maxZoom, is there then any way to block or specify Occlusion for the building, so that I can control where or what part of the building the user can enter?

Not really, think that the camera is "owned" by mapbox and Threebox basically syncs Three.js PerspectiveCamera. Movement of the camera view only depends on your interactions, so you can position anywhere. If what you want to do is to drive the camera to some concrete 3D objects, what I would recommend is to program that in the `SelectedChange` event, so then you can drive the camera position to an indoor point of view, but that doesn't avoid that the user would be able to move freely to other 3D objects using mouse or touch interactions

**Comment by ShaneTex** [comment]
Gotcha, I appreciate all the help
