### ISSUE TITLE
DRACO Loader

### ISSUE THREAD

**Issue by mobeen-asghar** [jscastro76/threebox#408]
Hi! Please add this feature

DRACO Loader for glb/gltf.

https://threejs.org/docs/#examples/en/loaders/DRACOLoader

**Comment by mobeen-asghar** [comment]
@jscastro76

**Comment by mobeen-asghar** [comment]
@jscastro76 Please need attention. If you don't have time please give some instructions. I need this for a project am working on. looking forward from you. Thanks

**Comment by mobeen-asghar** [comment]
@jscastro76  … Need your attention please.

**Comment by mobeen-asghar** [comment]
@jscastro76

**Comment by jscastro76** [comment]
This is a topic that was already evaluated and discussed [here](https://github.com/jscastro76/threebox/issues/117#issuecomment-747998263)
Long story short, no, DRACO is not in the roadmap as it implies to embed a bunch of extra libraries that will make Threebox grow importantly in size. 

I think [one of the forks of this project](https://github.com/murataka/threebox) already included DRACO, but using online libraries through `dracoLoader.setDecoderPath` which is an approach, but then the library wouldn't be anymore useful offline (which was one of my requirements from the very first day)
