### ISSUE TITLE
Callback when object location change

### ISSUE THREAD

**Issue by Adel-J** [jscastro76/threebox#41]
Hi @jscastro76 ,

Thank you for maintaining this plugin.

I'm looking to edit in soldier animation example, what I'm trying to do is to get callback for every coordinates on line; so when the 3d object moved to next coordinates on line I get callback to do any things.

I read all the docs nothing implement my intent, but I found [followPath](https://github.com/jscastro76/threebox/blob/master/docs/Threebox.md#followpath) is the best way to implement my goal just adding another callback fired every update.

I started implementing this on source code add this another callback but unfortunately callback always return at the end.

**So it is doable?
Am I in the right place "follow path" or there another way?**

P.S. the render function in "CustomLayerInterface" is the worst solution cause is "Called during a render frame allowing the layer to draw into the GL context." 

Update: after digging in the code I found the "follow path" based on duration not on the line and all coordinates convert to point, is that right?

**Comment by jscastro76** [comment]
Hi @Adel-J, 

If you need a callback every time the coords of an object change, definitely `followPath` is not the right place as it only creates the animation, but the steps are managed at [AnimationManager.update](https://github.com/jscastro76/threebox/blob/257a0bafc5f71f5aff8aa8816fb5bdda9ab76f23/src/Animation/AnimationManager.js#L381) creating an `objectState` that is sent to `object._setObject(objectState);`. So you could fire an event after that to be captured from the UI. Just as an idea...
```js
obj.dispatchEvent(new CustomEvent('ObjectMoved', { detail: objectState, bubbles: true, cancelable: true }));
```
Then you can subscribe to the event from the UI like this.
```js
tb.loadObj(options, function (model) {
	soldier = model.setCoords(origin);
	// Listening to the events
	model.addEventListener('ObjectMoved', onObjectMoved, false);
        ...
        ...
        ...
	tb.add(soldier);
})
```
and define an `onObjectMoved` function to manage whatever you want to do. In that way the event will only be fired when the object is moved through a followPath animation, on every step.

This seems as a potentially interesting event to add... I´ll add it to the backlog but depending my workload this may have less priority to be implemented.

**Comment by Adel-J** [comment]
Hi @jscastro76,

Thank you, this is great solution.
But as you mention this will be fired every steps in the vectors that created so it is going to have a lot of event making the map slower on the performance.

So can I know the index of current line of coordinates (path array) when the object on it from vector?

**Comment by jscastro76** [comment]
`options.path` contails the original path coordinates as a line geometry, but this example was created by peterqliu to make the car/avatar describe a curve as a spline that is defined in `options.pathCurve`. 

I think what you are looking for is this... It´s something I had in mind to incorporate from another [Threebox Fork from](https://github.com/akiosTerr/threebox) @akiosTerr
![image](https://user-images.githubusercontent.com/38470852/92715056-40a0a780-f35d-11ea-9285-da796e853445.png)

**Comment by Adel-J** [comment]
Yes, this is a part what I'm trying to do the problem with @akiosTerr fork he is convert path to line curve and this working fine usually when you have a "LineString" feature.
After trying the fork with polygon point it is work but[ every curve will have the same duration that set for hole path,](https://github.com/akiosTerr/threebox/blob/6fa3c3344dad065651f53245f8079c737ada535c/src/Animation/AnimationManager.js#L212) I will try to handle this.


Again thank you for you help.

**Comment by akiosTerr** [comment]
@Adel-J if you find way to make a constant velocity animation instead of a constant time duration, let me know, I was having trouble with this.
