### ISSUE TITLE
Angular and Threebox

### ISSUE THREAD

**Issue by joshnice** [jscastro76/threebox#42]
Hi, 

First of all thanks for maintaining Threebox and adding some great features!

In a previous post (https://github.com/jscastro76/threebox/pull/25#issuecomment-665537308) it was recommend that I created a simple Angular application to have a minimal reproducible example. In this application I have installed Mapbox and Threebox. The error gets thrown whenever the mouse hovers over the map, however I have also added a 3D model successfully with no errors. The error thrown is shown below.

![image](https://user-images.githubusercontent.com/36700042/92489279-876c9100-f1e7-11ea-94e8-ef100f7cbc83.png)

Example repo: https://github.com/joshnice/angular_threebox

In the index.html file there is commented out code of a script tag referencing mapbox.js, if this does not have comments around it then the error is not thrown. However if Mapbox is bundled with the Angular application as in this case, I don't think the error should be thrown.

Angular Version: 10.1.0
Mapbox-gl Version: 1.12.0
Threebox Version: 2.0.5 (latest)

**Comment by jscastro76** [comment]
Hi @joshnice 
I´ll take a look to it but it seems an issue with your bundle in Angular.

**Comment by luojiandan** [comment]
@joshnice I got the same error in vue. do you solved?

**Comment by jscastro76** [comment]
@joshnice did you finally solve this issue?? I took a look at the code but not being an advanced user in Angular, I couldn´t identify the issue. My feeling is that you will need to add an include to mapbox in Threebox.js file.

**Comment by joshnice** [comment]
@luojiandan hi, sorry I have not solved the issue. I have tried a few different things to solve it, such as trying to import it and including it in the scripts array inside the configuration file (this may just be an Angular thing). Unfortunately none of these ways seemed to work. Over the next few weeks I will be experimenting with React, Mapbox and Threebox so it will be interesting if the same issue occurs.

**Comment by jscastro76** [comment]
Hi @joshnice, @luojiandan 
This issue is solved, I'm pushing the changes to github
