### ISSUE TITLE
Create a method to override map.removeLayer

### ISSUE THREAD

**Issue by jscastro76** [jscastro76/threebox#43]
As mentioned in #39 [here](https://github.com/jscastro76/threebox/issues/39#issuecomment-685446200) map.removeLayer should also be able to remove the objects in the layer, but that´s not happening as the 3D objects are in tb.world.

**Comment by dianaow** [comment]
Could one possible way be this?

```
      map.removeLayer = function(id) { 
        this.tb.clear(true).then(d=>{
          console.log(d)
          map.style.removeLayer(id);
        })
      }
```

P.S How do i create a fork of your fork? (I have updated the code locally and am thinking of creating a PR for this)

**Comment by jscastro76** [comment]
> Could one possible way be this?
> 
> ```
>       map.removeLayer = function(id) { 
>         this.tb.clear(true).then(d=>{
>           console.log(d)
>           map.style.removeLayer(id);
>         })
>       }
> ```
> 
> P.S How do i create a fork of your fork? (I have updated the code locally and am thinking of creating a PR for this)

This will clear completely all the threebox objects in any layer, my approach for this is to consider there would be always multiple layers. I already have a draft for this method I’m working on other project.

Regarding the fork, you can do it from the main page of this repo, feel free to fork it.
