### ISSUE TITLE
disable or enable  dirLightHelper for realSunlight  

### ISSUE THREAD

**Issue by likeswinds** [jscastro76/threebox#44]
![image](https://user-images.githubusercontent.com/7099174/93058775-64882400-f6a2-11ea-9dfa-a848bb316829.png)
![image](https://user-images.githubusercontent.com/7099174/93059022-bc268f80-f6a2-11ea-801f-2307f439e963.png)

**Comment by jscastro76** [comment]
I wanted to make this optional, due to the lack of time for delivering the last release I couldn't do it. You can remove it in the meantime and I'll open a task with this.

**Comment by likeswinds** [comment]
I got it，thanks for your great work!

**Comment by jscastro76** [comment]
Hi @likeswinds!
Finally, realSunlightHelper is now a Threebox param to set when instancing, by default false. This is updated in [v2.0.9.](https://github.com/jscastro76/threebox/releases/tag/v.2.0.9)

**Comment by jscastro76** [comment]
Hi @likeswinds!
Finally, realSunlightHelper is now a Threebox param to set when instancing, by default false. This is updated in [v2.0.9.](https://github.com/jscastro76/threebox/releases/tag/v.2.0.9)
