### ISSUE TITLE
vue import threebox get error:(

### ISSUE THREAD

**Issue by luojiandan** [jscastro76/threebox#52]
@jscastro76 
I import threebox to my project,get error:(,what's wrong?
![image](https://user-images.githubusercontent.com/5663556/96250013-b6dd9d00-0fe0-11eb-9e83-efff2c1906c6.png)
![image](https://user-images.githubusercontent.com/5663556/96250000-b1805280-0fe0-11eb-9575-8f8d8d9df904.png)

the threebox.js in static folder,it's ok:
![image](https://user-images.githubusercontent.com/5663556/96249992-adeccb80-0fe0-11eb-897e-06feaafadac3.png)

![image](https://user-images.githubusercontent.com/5663556/96249982-a7f6ea80-0fe0-11eb-860e-7d7d3b5e8796.png)

**Comment by jscastro76** [comment]
As said in peterqliu site, Threebox is a Three.js plugin for Mapbox, Three.js is embedded, but not Mapbox that must be present in the context of the page executed. 

In your case, I don´t know the reason it's nor working in Vue. The bundle is not definitely being accessible at the level of the `mousePos` function execution context. You will probably need to fork this project and then add the needed include statement in Threebox.js file.

**Comment by jscastro76** [comment]
This was changed and now the point doesn't need of mapboxgl.Point
```js 
function mousePos(e) {
	var rect = canvas.getBoundingClientRect();
	return {
		x: e.originalEvent.clientX - rect.left - canvas.clientLeft,
		y: e.originalEvent.clientY - rect.top - canvas.clientTop
	};
}
```
