### ISSUE TITLE
same option,different coordinates

### ISSUE THREAD

**Issue by luojiandan** [jscastro76/threebox#53]
@jscastro76 
![image](https://user-images.githubusercontent.com/5663556/96250164-fd32fc00-0fe0-11eb-9634-8602f0583e80.png)

loadObj load many obj,but the option is same,just coordinate is different.
I change code like this,but only one model display.
![image](https://user-images.githubusercontent.com/5663556/96250176-03c17380-0fe1-11eb-803c-c9d6acea0f57.png)

**Comment by jscastro76** [comment]
You are using wrongly the callback and basically rewriting the coords before the object is finally created. 

If you want to create multiple objects you have to clone them through [`obj.duplicate`](https://github.com/jscastro76/threebox/blob/master/docs/Threebox.md#duplicate). You also have an example of how to do clone an object multiple times properly in [mercator.html](https://github.com/jscastro76/threebox/blob/master/examples/mercator.html).

Please, for next questions review first the documentation, it's made on that purpose.
