### ISSUE TITLE
Question: Why is this library not available on npm ?

### ISSUE THREAD

**Issue by PodaruDragos** [jscastro76/threebox#74]
I was wondering why this library is not available on npm. Integrating this with typescript and a frontend framework seems like a tedios job.

Are there any plans to add it ? Is there any plan to add typescript type definitions ?

**Comment by jscastro76** [comment]
@PodaruDragos thanks for the interest in having this fork of Threebox in npm, I've seen many threebox forks uploaded included the one from peterqliu, but all of them from +1 one year ago with the v0.2 only.

In my personal case it's not an option to install it from npm in my prod environment that´s why I kept it as an standalone resource to link as a simple script to any web server. But having said so, it's an option I was evaluating, indeed I was checking the requirements to do it. 

Migrating to typescript would be definitely a ton of extra work that I'm not able to manage so far, not sure if in the future I'll be forced to migrate it if my project requires it, so far I don't have any plan to migrate it.

**Comment by PodaruDragos** [comment]
You don't need to actually migrate the code to typescript for type definitions.
If i will be using this i am willing to contribute to the typings if you are on board with it.

**Comment by jscastro76** [comment]
@PodaruDragos Super happy to have a volunteer as contributor for that task if you want to lead it from a branch. I will only need a serious testing once we start to merge as I use this project in production, so I cannot approve PR if that breaks my project.

BTW I have already upload the plugin to npm as [threebox-plugin](https://www.npmjs.com/package/threebox-plugin). Thanks for the suggestion, I was already thinking on it but you pushed me forward.
